
var ingilizceturkce = {
    "A wide range of": "Çok çeşitli",
    "Accept": "Kabul et-",
    "Accident": "Kaza",
    "Addiction": "Bağımlılık",
    "Admit": "İtiraf et-",
    "Agency": "Acente",
    "Amount": "Miktar",
    "Anchor": "Demir",
    "Announce": "Duyur-",
    "Anzac": "Anzak",
    "Applause": "Alkış",
    "Apply": "Uygula-",
    "Approach": "Yaklaş-",
    "Archaeologist": "Arkeolog",
    "At Least": "En Az",
    "Attack": "Saldır-",
    "Attend": "Katıl-",
    "Attract": "Çek-",
    "Bangladesh": "Bangladeş",
    "Be fed up with": "-Den bık-",
    "Behavior": "Davranış",
    "Believe": "İnan-",
    "Bite": "Isır-",
    "Body": "Vücut",
    "Both ... and": "Hem... hem",
    "Boy": "Çocuk",
    "Brand": "Marka",
    "Bring": "Getir-",
    "Broadcast": "Yayınla-",
    "Call": "Ara-",
    "Cell": "Hücre",
    "Chair": "Sandalye",
    "Change": "Değiş-",
    "Childhood": "Çocukluk",
    "Chinese": "Çinli",
    "Citizen": "Vatandaş",
    "Claim": "İddia",
    "Climbing": "Tırmanma",
    "Cloth": "Bez",
    "Coach": "Koç",
    "Coast Guard Vessel": "Sahil Güvenlik Gemisi",
    "Cocoa Bean": "Kakao Çekirdeği",
    "Collect": "Topla-",
    "Company": "Şirket",
    "Complain": "Şikâyet et-",
    "Complete": "Tamamla-",
    "Concert": "Konser",
    "Conduct": "Yürüt-",
    "Control": "Yönet-",
    "Corner": "Köşe",
    "Crash": "Çarp-",
    "Crew": "Mürettebat",
    "Criminal Investigation": "Cezai Soruşturma",
    "Criminal": "Suçlu",
    "Cup": "Kupa",
    "Curious": "Meraklı",
    "Customer": "Müşteri",
    "Day And Night": "Gece gündüz",
    "Decide": "Karar ver-",
    "Decorate": "Dekore et-",
    "Definitely": "Mutlaka",
    "Defender": "Savunma Oyuncusu",
    "Delighted": "Memnun",
    "Deliver": "Teslim etmek",
    "Deserve": "Hak et-",
    "Destroy": "Yık-",
    "Diagnose": "Tanı kon-",
    "Die of": "-Den öl-",
    "Dietitian": "Diyetisyen",
    "Different": "Farklı",
    "Disease": "Hastalık",
    "Distract": "Dikkat dağıt-",
    "Distribute": "Dağıt-",
    "Documents": "Evraklar",
    "Drop": "At-",
    "Drown": "Boğul-",
    "Dry food item": "Kuru gıda maddesi",
    "Eastern Anatolia": "Doğu Anadolu",
    "Easy": "Kolay-",
    "Eliminate": "Yok et-",
    "Employment": "İstihdam",
    "End with": "ile sonlan-",
    "Endangered": "Nesli tükenmekte olan",
    "Enlighten": "Aydınlat",
    "Enough": "Yeterince",
    "Event": "Olay",
    "Ever": "Hiç bu zamana kadar",
    "Exam": "Sınav",
    "Excuse": "Bahane",
    "Expert": "Uzman",
    "Experiment": "Deney",
    "Fatal": "Ölümcül",
    "Favorite": "En çok sev-",
    "Find": "Bul-",
    "Fine": "Para cezası",
    "Fire": "Kov-",
    "Firm": "Şirket",
    "Flat": "Apartman dairesi",
    "Flexibility": "Esneklik",
    "Forget": "Unut-",
    "Found": "Kur-",
    "Future": "Gelecek",
    "Gain": "Kazan-",
    "German": "Alman",
    "Get red": "Kızar-",
    "Get": "Al-",
    "Giant": "Dev",
    "Gigantic": "Devasa",
    "Give up": "Vazgeç-",
    "Give": "Ver-",
    "Go bankrupt": "İflas et-",
    "Government": "Devlet",
    "Great": "Büyük",
    "Grow up": "Yetişmek",
    "Guest": "Misafir",
    "Harm": "Zarar ver-",
    "Have a breakfast": "Kahvaltı yap-",
    "Hazardous": "Tehlikeli",
    "Hear": "Duy-",
    "Heart attack": "Kalp krizi",
    "Heavy": "Ağır",
    "High": "Yüksek",
    "Holiday": "Tatil",
    "Hot": "Sıcak",
    "Housebreaker": "Hırsız (ev soyan)",
    "Human being": "İnsanoğlu",
    "Hurt": "İncit-",
    "Immigrate": "Göç et-",
    "Immune system": "Bağışıklık sistemi",
    "In fragments": "Parçalar halinde",
    "In front of": "-Nın önünde",
    "In Number": "Sayıca",
    "Incisive": "Dokunaklı",
    "Include": "İçer-",
    "Infectious": "Bulaşıcı",
    "Inform": "Bilgilendir-",
    "Insert": "Yerleştir-",
    "Inspection Firm": "Denetim Firması",
    "Inspection": "Denetleme",
    "Inspire": "İlham ver-",
    "Intense": "Yoğun",
    "Introvert": "İçe dönük",
    "Issue": "Mesele",
    "Judge": "Yargıç",
    "Know": "Tanı-",
    "Land": "Toprak",
    "Landlord": "Mülk sahibi",
    "Lead to": "-E sebep ol-",
    "Leading expert": "Önde gelen uzman",
    "Leaves": "Ayrılmak",
    "Lie down": "Uzan-",
    "Live": "Yaşa-",
    "Locate": "Yerleştir-",
    "Long": "Uzun",
    "Look through": "Gözden geçir-",
    "Look": "Ara-",
    "Lose": "Kaybet-",
    "Love": "Sev-",
    "Made": "Yap-",
    "Management": "Yönetim",
    "Mansion": "Malikane",
    "Mark": "Not",
    "Measure": "Önlem",
    "Mental": "Ruhsal",
    "Meteorite": "Göktaşı",
    "Microchip": "Mikroçip",
    "Moist": "Nemli",
    "Mostly": "Çoğunlukla",
    "Naughty": "Yaramaz",
    "News": "Haber",
    "Nonsense": "Saçmalık",
    "Observe": "Gözlemle-",
    "Only": "Sadece",
    "Order": "Sipariş ver-",
    "Ottoman": "Osmanlı",
    "Overwhelmed": "Bunalmış",
    "Paper": "Kâğıt",
    "Participate": "Yer al-",
    "Pass by": "Geç-",
    "Patriot": "Vatansever",
    "Perfect": "Mükemmel",
    "Perform": "Uygula-",
    "Physicist": "Fizikçi",
    "Pick": "Seç-",
    "Place into": "Yerleş-",
    "Pocket": "Cep",
    "Position": "Yerleştir-",
    "Prepare": "Hazırla-",
    "Prestigious": "Prestijli",
    "Priceless": "Paha biçilemez",
    "Proclaim": "Beyan et-",
    "Properly": "Doğru düzgün",
    "Prove": "Kanıtla-",
    "Public": "Halk",
    "Punish": "Ceza ver-",
    "Pupil": "Öğrenci",
    "Purchase": "Satın al-",
    "Purple": "Mor",
    "Reality": "Gerçeklik",
    "Recruit": "İşe al-",
    "Referee": "Hakem",
    "Refugee Camp": "Mülteci kampı",
    "Regime": "Rejim",
    "Regular": "Düzenli",
    "Reign": "Yönetim",
    "Remain": "Kal-",
    "Remember": "Hatırla-",
    "Renaissance": "Rönesans",
    "Rent": "Kirala-",
    "Repair": "Onar-",
    "Replace": "Yerini al-",
    "Rescue Team": "Kurtarma ekibi",
    "Research": "Araştırma",
    "Reveal": "Ortaya koy-",
    "Right time": "Doğru zaman",
    "Right": "Haklı",
    "Rob": "Soy-",
    "Robber": "Soyguncu",
    "Rucksack": "Sırt çantası",
    "Same": "Aynı",
    "Save": "Biriktir-",
    "Scene": "Sahne",
    "Scholarship": "Burs",
    "See": "Gör-",
    "Set up": "Kur-",
    "Sheriff": "Şerif",
    "Shot": "Çek-",
    "Shut down": "Kapat-",
    "Sign": "İmzala-",
    "Since": "-Den beri",
    "Sing": "Şarkı söyle-",
    "Singer": "Şarkıcı",
    "Smile": "Gül-",
    "Son": "Oğul",
    "Southeast": "Güney doğu",
    "Speak": "Konuş-",
    "Species": "Tür",
    "Start": "Başla-",
    "Stay": "Kal-",
    "Strong": "Güçlü",
    "Study": "Çalış-",
    "Succeed": "Kazan-",
    "Suggest": "Öner-",
    "Suitcase": "Valiz",
    "Support": "Desteklemek",
    "Surprising": "Şaşırt-",
    "Survive": "Hayatta kal-",
    "Substance": "Madde",
    "Take A Shower": "Duş al-",
    "Take": "Al",
    "Talented": "Yetenekli",
    "Tax": "Vergi",
    "Teach": "Öğret-",
    "Template": "Taslak",
    "Terrible": "Kötü",
    "Test": "Test et-",
    "The Earth": "Dünya",
    "Third": "Üçüncü",
    "Though": "Rağmen",
    "Tidal zone": "Gelgit bölgesi",
    "Tournament": "Turnuva",
    "Treasure hunter": "Hazine avcısı",
    "Trouble": "Sıkıntı",
    "Try": "Çalış-",
    "Twin Towers": "İkiz Kuleler",
    "Uncle": "Amca",
    "Uncontrolled": "Kontrolsüz",
    "Understand": "Anla-",
    "Unique": "Eşsiz",
    "User": "Kullanıcı",
    "Various": "Çeşitli",
    "View": "Gör-",
    "Village": "Köy",
    "Violate": "İhlal et-",
    "Visit": "Ziyaret et-",
    "Visited": "Gidilmiş",
    "Wake": "Uyandırmak",
    "Wall": "Duvar",
    "Wallet": "Cüzdan",
    "Watch": "İzlemek",
    "Water turbine": "Su çarkı",
    "We all": "Hepimiz",
    "Weather": "Hava",
    "Weave": "Doku-",
    "Wife": "Eş (kadın)",
    "Wipe": "Sil-",
    "Without": "Olmaksızın",
    "Witness": "Şahit ol-",
    "Work": "Çalış-",
    "Yesterday": "Dün"
};
