var turkceingilizce = {
    "Açıklama": "Explanation",
    "Açıklığa Kavuşturmak": "Clarify",
    "Adam": "Man",
    "Adanmak": "Dedicate",
    "Affet-": "Forgive",
    "Aile": "Family",
    "Akşam Yemeği": "Dinner",
    "Akşam": "Evening",
    "Al-": "Get, Take",
    "Albay": "Colonel",
    "Alerjik": "Allergic",
    "Alfabe": "Alphabet",
    "Altın": "Gold",
    "Amaç": "Aim",
    "Amca": "Uncle",
    "Ameliyat": "Surgery",
    "Amfi": "Amplifier",
    "Anahtar": "Key",
    "Anlaşma": "Treaty",
    "Ara-": "Call",
    "Araba": "Car",
    "Arazi": "Land",
    "Arkadaş": "Friend",
    "Arşiv": "Archive",
    "Aşçı": "Chef",
    "Atmak": "Throw",
    "Avantaj": "Advantage",
    "Avukat": "Lawyer",
    "Ayna": "Mirror",
    "Ayrımcılık": "Discriminating",
    "Bağlan-": "Connect",
    "Bahçe": "Garden",
    "Balık": "Fish",
    "Başar-": "Manage",
    "Başkan": "President",
    "Bekle-": "Wait",
    "Belge": "Document",
    "Besin Değeri": "Nutritive Value",
    "Bırak-": "Leave",
    "Bildirim": "Notification",
    "Bilgili": "Knowledgeable",
    "Bilgisayar": "Computer",
    "Bir Koku Yarat": "Create a Stink",
    "Bir şey": "Something",
    "Birden": "Sudden",
    "Bitkisel": "Herbal",
    "Boğaz": "Throat",
    "Bölge": "Region",
    "Bürokrat": "Bureaucrat",
    "Cesur": "Brave",
    "Çaba": "Strive",
    "Çağ": "Era",
    "Çekmece": "Drawer",
    "Çeşni karışımı": "Seasoning",
    "Çevir-": "Transform",
    "Çevrimiçi": "Online",
    "Çıkart-": "Extract",
    "Çılgın": "Crazy",
    "Çocuk": "Child",
    "Çocukluk": "Childhood",
    "Çöz-": "Solve",
    "Çöp kutusu": "Rubbish bin",
    "Çöp": "Rubbish",
    "Daha Fazla": "More",
    "Daire": "Circle",
    "Dava aç-": "File",
    "Değerlendir-": "Evaluate",
    "Değiştir": "Alter, Change",
    "Den dolayı": "Because of",
    "Denetleme": "Inspection",
    "Denge": "Balance",
    "Dernek": "Association",
    "Ders": "Lesson",
    "Devlet": "Government, State",
    "Devre Arası": "Half Time",
    "Dijital": "Digital",
    "Dil": "Language",
    "Dinle-": "Listen, Listen to",
    "Doktor": "Doctor",
    "Dosya": "File",
    "Dua Et-": "Pray",
    "Durum": "Status",
    "Dükkan Sahibi": "Shop Keeper",
    "Düşüncesiz": "Thoughtless",
    "Düzenli-": "Regular",
    "Eğitim": "Education, Training",
    "Ekonomik": "Economic",
    "Elçi": "Ambassador",
    "Eleştir-": "Criticise",
    "Emekle-": "Crawl",
    "Erkek Arkadaş": "Boyfriend",
    "Erken": "Early",
    "Eski": "Old",
    "Eş": "Spouse",
    "Fakir": "Poor",
    "Fark etmek": "Notice",
    "Favori": "Favorite",
    "Film": "Movie",
    "Finansal": "Financial",
    "Fotoğraf": "Photograph",
    "Gazeteci": "News Reporter",
    "Gazeteler": "Newspapers",
    "Geç": "Late",
    "Geçen": "Last",
    "Gel-": "Come",
    "Gelecek": "Future",
    "Genel": "General",
    "Geniş": "Broad",
    "Gerçek": "Real, Truth",
    "Getir-": "Bring",
    "Giriş Salonu": "Foyer",
    "Giriş": "Entrance",
    "Gizli": "Secret",
    "Gönder-": "Send",
    "Gör-": "See",
    "Göster-": "Show",
    "Göze al-": "Venture",
    "Güven-": "Trust",
    "Güvenlik": "Security",
    "Haber": "News",
    "Hak": "Right",
    "Hakem": "Referee",
    "Halk": "Public",
    "Harca-": "Spend",
    "Harika": "Awesome",
    "Hasta": "Patient",
    "Hata": "Mistake",
    "Hayal": "Dream",
    "Hayati": "Vital",
    "Hayran": "Fan",
    "Hayvan": "Animal",
    "Hazırla-": "Prepare",
    "Herhangi Bir Şey": "Anything",
    "Hesap": "Account",
    "Hukuk": "Law",
    "İfade": "Expression",
    "İlk Olarak": "Firstly",
    "İntikam": "Revenge",
    "İstemek": "Want",
    "İstifa": "Resign",
    "İstikrarsızlık": "Instability",
    "İşsizlik": "Unemployment",
    "İtibar": "Reputation",
    "İyileştir-": "Heal",
    "Kaç-": "Escape",
    "Kalem": "Pencil",
    "Kapalı": "Closed",
    "Kapat-": "Close",
    "Kapı": "Door",
    "Kapsamlı": "Extensive",
    "Karar": "Decision",
    "Kasa": "Safe",
    "Kasaba": "Town",
    "Kasım": "November",
    "Kaybet-": "Lose",
    "Kız evlat": "Daughter",
    "Kimya": "Chemistry",
    "Klinik": "Clinic",
    "Komşu": "Neighbor",
    "Konferans": "Conference",
    "Konu": "Topic",
    "Koşullar": "Conditions",
    "Koy-": "Put",
    "Kudüs": "Jerusalem",
    "Kurbağa": "Frog",
    "Kurmak": "Establish",
    "Kurs": "Course",
    "Kurul": "Assembly",
    "Küçük": "Little",
    "Küresel": "Global",
    "Landscape": "Manzara",
    "Liste": "List",
    "Maç": "Match",
    "Madenci": "Miner",
    "Mahalle": "Neighborhood",
    "Mahkeme": "Court",
    "Manuel": "Manual",
    "Medyum": "Psychic",
    "Mesele": "Matter",
    "Moda Tasarımcısı": "Fashion Designer",
    "Mühendis": "Engineer",
    "Müşteri": "Client",
    "Not": "Note",
    "Oda": "Room",
    "Oğul": "Son",
    "Oluştur-": "Create",
    "Onaylamak": "Approve",
    "Ortak": "Co Partner",
    "Ortaya Çık-": "Arise",
    "Otel": "Hotel",
    "Oturmak": "Sit",
    "Oyuncu": "Actress",
    "Oyuncu": "Player",
    "Ödeme": "Payment",
    "Ödev": "Assignment",
    "Ödül": "Award",
    "Öğren-": "Learn",
    "Öğrenci": "Student",
    "Öğretim Görevlisi": "Lecturer",
    "Öğretmen": "Teacher",
    "Ön Okuma": "Pre Reading",
    "Öne Çıkan": "Prominent",
    "Öneri": "Advice, Suggest",
    "Önlem": "Precaution",
    "Öp-": "Kiss",
    "Paket Servis": "Take Out",
    "Papa": "Pope",
    "Para": "Money",
    "Patron": "Patron",
    "Paylaş": "Share",
    "Plan": "Plan",
    "Platform": "Platform",
    "Proje": "Project",
    "Promosyon": "Promotion",
    "Psikolojik": "Psychological",
    "Puan": "point",
    "Radikal": "Radical",
    "Rahatlat-": "Comfort",
    "Rahatsız et-": "Disturb",
    "Raket": "Racket",
    "Rapor": "Report",
    "Reaksiyon": "Reaction",
    "Refah": "Welfare",
    "Reklam Ajansı": "Advertising Agency",
    "Resepsiyon": "Reception",
    "Resmi": "Official",
    "Röportaj": "Interview",
    "Saat": "Hour, Time",
    "Sabah": "Morning",
    "Saçmalık": "Nonsense",
    "Sağ": "Right",
    "Sağlık": "Health",
    "Sağlıklı": "Healthy",
    "Sahil": "Coast",
    "Sahip (Kişi)": "Owner",
    "Sahne": "Stage",
    "Sakla-": "Keep, Hide",
    "Salon": "Hall",
    "Samimiyetsiz": "Insincere",
    "Satranç": "Chess",
    "Savcı": "Prosecutor",
    "Sebep": "Reason",
    "Seç-": "Select",
    "Seçenek": "Option",
    "Seçim": "Election",
    "Sev-": "Love",
    "Sigara İç-": "Smoking",
    "Sipariş": "Order",
    "Sistem": "System",
    "Siyasetçi": "Politician",
    "Siyasi": "Political",
    "Slogan": "Slogan",
    "Sokak": "Street",
    "Son": "Last",
    "Sonuç": "Consequential, result",
    "Soru": "Question",
    "Sorumsuz": "Irresponsible",
    "Sorun": "Issue, Problem",
    "Sosyal": "Social",
    "Spor": "Sports",
    "Suç Örgütü": "Crime Syndicate",
    "Sunum": "Presentation",
    "Sustur-": "Hush",
    "Süreç": "Process",
    "Swot Analizi": "Swot Analysis",
    "Şampiyon": "Champion",
    "Şans": "Luck",
    "Şarkıcı": "Singer",
    "Şartlar": "Terms",
    "Şaşırtıcı": "Astonishing",
    "Şehir": "City",
    "Şiddet": "Violence",
    "Şifre": "Password",
    "Şimdiye Kadar": "So Far",
    "Şirket": "Company",
    "Şoför": "Chauffeur",
    "Şut": "Shot",
    "Tabak": "Plate",
    "Taht": "Throne",
    "Takım": "Team",
    "Takip Et-": "Follow",
    "Taksit": "Instalment",
    "Talep": "Demand",
    "Tamamen": "Completely",
    "Tamir": "Repair",
    "Tanık": "Witness",
    "Tanıt-": "Promote",
    "Taraftar": "Supporter",
    "Tarihi": "Historical",
    "Konak": "Mansion",
    "Tartış-": "Discuss",
    "Tasarım": "Creation",
    "Taşı-": "Carry",
    "Taşın-": "Move",
    "Tavsiye": "Recommend",
    "Tazelen-": "Refresh",
    "Tek Başıma": "On My Own",
    "Teklif": "Offer, Proposal",
    "Teknisyen": "Technician",
    "Test Sonuçları": "Test Results",
    "Teşekkürler": "Thanks",
    "Toplantı": "Meeting",
    "Toplum": "Society",
    "Trendy": "Fashionable",
    "Tut-": "Hold",
    "Türk": "Turkish",
    "Ufak": "Little",
    "Unut-": "Forget",
    "Uyanık": "Awake",
    "Uygula-": "Apply",
    "Uymak": "Comply",
    "Uzaktan Kumanda": "Remote Control",
    "Uzlaş-": "Reconcile",
    "Ünlü": "Famous",
    "Ürkütücü": "Terrifying",
    "Ürün": "Product",
    "Üz-": "Upset",
    "Vaka": "Case",
    "Varış": "Arrival",
    "Vatandaş": "Citizen",
    "Ver-": "Give",
    "Virüs": "Virus",
    "Yabancı": "Foreign, Stranger",
    "Yakın": "Close",
    "Yansıma": "Reflection",
    "Yap-": "Make",
    "Yararlı": "Beneficial",
    "Yarı müstakil": "Semi-Detached",
    "Yarın": "Tomorrow",
    "Yasadışı": "İllegal",
    "Yaşam": "Life",
    "Yatırım Yap-": "Invest",
    "Yayınla-": "Release",
    "Yay-": "Disperse",
    "Yazılım": "Software",
    "Ye-": "Eat",
    "Yemek": "Food",
    "Yıkım": "Ruin",
    "Yıl": "Year",
    "Yol": "Way",
    "Yolla-": "Send",
    "Yorum": "Comment",
    "Yönetici": "Director, Manager",
    "Yüz-": "Swim",
    "Yüzük": "Ring",
    "Zaman Geçir-": "Spend Time",
    "Zaman": "Time",
    "Zil": "Bell",
    "Zirve": "Summit",
    "Ziyaret Et-": "Visit",
    "Zor": "Difficult",
    "Zorla-": "Force",
    "Zorunlu": "Obligatory"
};