
var turkceingilizce = {
    "abi": "brother",
    "acı": "sad",
    "açlık": "hunger",
    "ad": "name",
    "ada": "island",
    "adam": "man",
    "adamlar": "men",
    "ağrımak": "ache",
    "aile": "family",
    "akıl": "mind",
    "akşam": "evening",
    "alkol": "alcohol",
    "almak": "take",
    "alman": "german",
    "ameliyat": "surgery",
    "ana": "main",
    "anahtar": "key",
    "anne": "mother",
    "araç": "vehicle",
    "arkadaş": "friend",
    "arkadaş": "mate",
    "asistan": "assistant",
    "at": "horse",
    "atmosfer": "atmosphere",
    "ay": "month",
    "ayırmak": "spare",
    "baba": "father,dad",
    "bahçe": "garden",
    "bahsetmek": "mention",
    "bakan": "president",
    "balayı": "honeymoon",
    "balık": "fish",
    "balkon": "balcony",
    "barışçıl": "peaceful",
    "baş parmak": "thumb",
    "başarı": "success",
    "başkan": "president",
    "bebek": "baby",
    "belirlemek": "determine",
    "beslemek": "feed",
    "bırakmak": "leave",
    "bilgisayar": "computer",
    "bitirmek": "finish",
    "bomba": "bomb",
    "bombacı": "bomber",
    "bozuk": "rotten",
    "bölge": "zone",
    "bu": "this",
    "bugün": "today",
    "bulmak": "find",
    "buluşmak": "meet",
    "büyüleyici": "fascinating",
    "büyük": "big",
    "cam": "glass",
    "cihaz": "device",
    "çadır": "tent",
    "çatı": "roof",
    "çiçek": "flower",
    "çocuk": "kid,child",
    "çözmek": "solve",
    "dahi": "genius",
    "dakika": "minute",
    "dal": "branch",
    "danışman": "counsellor",
    "davet etmek": "invite",
    "değerli": "precious",
    "değiştirmek": "change",
    "delik": "hole",
    "-den sonra": "after",
    "denemek": "try",
    "deprem": "earthquake",
    "ders": "lecture",
    "destan": "epic",
    "detay": "detail",
    "device": "cihaz",
    "devlet": "state",
    "dikkatli bir şekilde": "carefully",
    "dosya": "file",
    "düğme": "button",
    "düşman": "enemy",
    "düşünce": "thought",
    "düzenlemek": "organise",
    "düzenli olarak": "regularly",
    "düzgün": "proper",
    "-e göre": "according to",
    "eğitim": "education",
    "el": "hand",
    "elma": "apple",
    "emir": "command",
    "enemy": "düşman",
    "eski": "old",
    "eşşek": "donkey",
    "ev": "house",
    "fabrika": "factory",
    "fedakar": "devoted",
    "film": "movie",
    "firma": "firm",
    "galibiyet": "victory",
    "garip": "strange",
    "geçirmek": "spend",
    "geçmek": "pass",
    "genç": "young",
    "gerçek": "truth",
    "gergin": "tense",
    "getirmek": "bring",
    "gezi": "trip",
    "giriş": "entrance",
    "gitmek": "go",
    "gizli": "hidden, secret",
    "gol": "goal",
    "göğüs kafesi": "rib cage",
    "göndermek": "send",
    "görev": "duty",
    "görmek": "see",
    "göstermek": "show",
    "grup": "group",
    "güçlü": "strong",
    "gün": "day",
    "güvercin": "pigeon",
    "güzel": "beautiful",
    "hafta içi": "weekday",
    "hafta sonu": "weekend",
    "hafta": "week",
    "harcamak": "spend",
    "harita": "map",
    "hasta": "patient",
    "hata": "error",
    "hava": "weather",
    "hayat": "life",
    "hazırlamak": "prepare",
    "her": "every",
    "her gün": "every day",
    "hırsız": "thief",
    "Isıtıcı": "heater",
    "ısrarcı bir şekilde": "insistently",
    "ıssız": "desolate",
    "idam": "execution",
    "ihtiyar": "oldman",
    "ikna etmek": "convince",
    "ilaç": "pill",
    "ilaç": "medicine",
    "ilginç": "amazing",
    "inatçı": "stubborn",
    "insanlar": "people",
    "intihar": "suicide",
    "ip": "rope",
    "iptal etmek": "cancel",
    "işgal etmek": "occupy",
    "kaba": "rude",
    "kader": "destiny",
    "kadın": "woman",
    "kadınlar": "women",
    "kafa": "head",
    "kafile": "cortege",
    "kahve": "coffee",
    "kalmak": "stay",
    "kamera": "camera",
    "kapatmak": "shut",
    "kaptan": "captain",
    "karakter": "character",
    "karar": "decision",
    "karın": "stomach",
    "kart": "card",
    "kaygan": "slippery",
    "kazanmak (para)": "earn",
    "kazanmak": "win",
    "kedi": "cat",
    "kenar": "side",
    "kisa": "short",
    "kibar": "kind",
    "kimlik numara": "identity number",
    "kitap": "book",
    "klinik": "clinic",
    "kolonya": "cologne",
    "kopya çekmek": "cheat",
    "koşul": "condition",
    "kötü": "bad",
    "köy": "village",
    "kültür": "culture",
    "kütüphane": "library",
    "lie": "uzanmak",
    "lig": "league",
    "liste": "list",
    "logo": "logo",
    "lokanta": "restaurant",
    "look": "görünmek",
    "maç": "match",
    "mavi": "blue",
    "meat": "et",
    "medya": "media",
    "memleket": "fatherland",
    "merkez": "center",
    "meşgul": "busy",
    "mevcut": "existent",
    "meydana gelmek": "occur",
    "millet": "nation",
    "milli": "national",
    "minik": "little",
    "muhabbet kuşu": "lovebird",
    "mücadele": "struggle,challenge",
    "müdür": "manager",
    "mühendis": "engineer",
    "mürekkep": "ink",
    "müsait": "available",
    "müsteşar": "undersecretary",
    "müşahede": "observation",
    "müşteri": "customer",
    "müze": "museum",
    "net": "clear",
    "numara": "number",
    "oda": "room",
    "oğul": "son",
    "okul": "school",
    "okumak": "read",
    "ordu": "army",
    "oyuncu": "player",
    "ödev": "homework",
    "ödül": "prize",
    "öğrenci": "student",
    "öğretmen": "teacher",
    "ölmüş": "dead",
    "önemli": "important",
    "önlem": "precaution",
    "örümcek korkusu": "arachnophobia",
    "pamuk": "cotton",
    "para": "money",
    "pastane": "patisserie",
    "patlama": "explosion",
    "peçete": "tissue",
    "proje": "project",
    "reddetmek": "reject",
    "resim": "picture",
    "rüya": "dream",
    "sabah": "morning",
    "saç": "hair",
    "saklamak": "keep",
    "savaş": "war",
    "savcı": "prosecutor",
    "saygı": "respect",
    "sayı": "number",
    "sessiz": "silent",
    "sevmek": "love",
    "sinav": "exam",
    "sihirbaz": "wizard",
    "sihirli": "magical",
    "sokak": "street",
    "sormak": "ask",
    "sorun": "problem",
    "söylemek": "tell",
    "söz vermek": "promise",
    "sözcü": "spokesman",
    "special": "özel",
    "su": "water",
    "sunum": "presentation",
    "sükunet": "silence",
    "süpürge": "broom",
    "süre": "time",
    "sürmek": "drive",
    "sürücü": "driver",
    "süt": "milk",
    "şirket": "company",
    "şişe": "bottle",
    "şimdi": "now",
    "şirin": "cute",
    "takım": "team",
    "talep etmek": "demand",
    "tarihi": "historical",
    "tartışmak": "argue",
    "tasfiye etmek": "disband",
    "taş": "stone",
    "taşımak, hareket etmek": "move",
    "tatışmak": "discuss",
    "tatil": "holiday",
    "tavsiye": "advise",
    "teklif": "offer",
    "tekne": "boat",
    "telefon": "telephone",
    "temel": "fundamental",
    "temin etmek": "get",
    "terk etmek": "leave",
    "teslim olmak": "surrender",
    "ticaret": "trade",
    "timsah": "crocodile",
    "toplantı": "meeting",
    "tren": "train",
    "tüketmek": "consume",
    "amca": "uncle",
    "ülke": "country",
    "ünlü": "famous",
    "ürkek": "shy",
    "ütü": "iron",
    "uzanmak": "lie",
    "vermek": "give",
    "virüs": "virus",
    "yabancı": "foreign",
    "yağmur": "rain",
    "yağmurlu": "rainy",
    "yakalamak": "arrest",
    "yalvarmak": "beg",
    "yan etki": "side effect",
    "yapmak": "do",
    "yaratık": "monster",
    "yarın": "tomorrow",
    "yarış": "race",
    "yasa": "law",
    "yaşam": "life",
    "yatırım": "investment",
    "yatırımcı": "investor",
    "yavru": "baby",
    "yaz": "summer",
    "yazıcı": "printer",
    "yazmak": "write",
    "yemek yemek": "eat",
    "yemek": "meal",
    "yeni": "new",
    "yer": "place",
    "yetenekli": "talented",
    "yol": "road",
    "yönetmen": "director",
    "yürümek": "walk",
    "zarf": "envelope",
    "zor": "hard"
};
