
var turkceingilizce = {
    "Aday": "Candidate",
    "Ağırlık": "Weight",
    "Al-": "Get, Receive, Take",
    "Alkış": "Applaud",
    "Anı, Hatıra": "Memory",
    "Ani": "Sudden",
    "Apartman sakini": "Apartment resident",
    "Ara-": "Look for",
    "Asistan": "Assistant",
    "Atık su": "Waste water",
    "Ayrıl-, Terk et-": "Leave",
    "Bağlan-": "Connect",
    "Baharatlı": "Spicy",
    "Bak-": "Look",
    "Başarı": "Success",
    "Başkan": "Minister",
    "Batır-": "Stab",
    "Baya": "Quite",
    "Bekle-": "Expect",
    "Beraber": "Together",
    "Berbat": "Terrible",
    "Beyazlat-": "Whiten",
    "Beyin": "Brain",
    "Bilgilendir-": "Inform",
    "Bilgisayar Korsanı": "Hacker",
    "Bilim insanı": "Scientist",
    "Bilim": "Science",
    "Bir sayfa uzunlukta": "One page long",
    "Bir Süreliğine": "For a while",
    "Biraz": "A bit",
    "Boşluk": "Gap",
    "Boya-": "Paint",
    "Brezilyalı": "Brazilian",
    "Bul-": "Find",
    "Büyük": "Great",
    "Büyü-": "Grow up",
    "Büyüle-, Hayran bırak-": "Fascinate",
    "Büyüleyici": "Fascinating",
    "Cam": "Glass",
    "Ceket": "Jacket",
    "Cennet": "Paradise",
    "Cevap": "Answer",
    "Cihaz": "Device",
    "Cinayet": "Murder",
    "Çabukça, Hızlıca": "Quickly",
    "Çağ, Dönem": "Period",
    "Çağır-": "Summon",
    "Çalışkan": "Hardworking",
    "Çamaşır makinesi": "Washing machine",
    "Çarşamba": "Wednesday",
    "Çatı": "Roof",
    "Çay seti": "Tea set",
    "Çay": "Tea",
    "Çiçek": "Flower",
    "Çoğunluk": "Majority",
    "Çok, Baya": "Really",
    "Dağınıklık, Karışıklık": "Mess",
    "Dal-": "Plough into",
    "Değerli": "Valuable",
    "Demle-": "Brew",
    "-Den kaçın": "Avoid",
    "Depresyon": "Depression",
    "Derbi": "Derby",
    "Derece": "Degree",
    "Ders Vakti": "Class Time",
    "Devlet Başkanı": "President",
    "Devrim yarat": "Revolutionize",
    "Dikkat et-": "Pay attention",
    "Dikkatli": "Careful",
    "Dinozor": "Dinosaur",
    "Diş": "Tooth",
    "Doğ-": "Born",
    "Doğum günü": "Birthday",
    "Dolaş-": "Wander",
    "Dosya": "File",
    "Dur-": "Stop",
    "Duy-": "Hear",
    "Dünya": "World",
    "-Den düş-": "Fall off",
    "Düşür-, Bırak-": "Drop",
    "Düzen": "Regulation",
    "-E rağmen": "Despite",
    "-E Var-": "Arrive at",
    "Ekonomik Kriz": "Economical crisis",
    "Emin": "Sure",
    "Empati": "Empathy",
    "Erkek kardeş, Ağabey": "Brother",
    "Erken": "Early",
    "Ev": "House",
    "Evlen-": "Get married",
    "Fakir, Yoksul": "Poor",
    "Favori": "Favorite",
    "Feribot": "Ferry",
    "Fonksiyon": "Function",
    "Fren yap-": "Put on the brake",
    "Garanti et-": "Assure",
    "Geç-": "Pass",
    "Geçen hafta": "Last week",
    "Geçerli": "Valid",
    "Geçmişe": "Back to the past",
    "Gel-": "Come",
    "Geleneksel Yemek": "Traditional Food",
    "Gemi Sahibi": "Ship-Owner",
    "Geri gel-": "Come back",
    "Geri, Arka": "Back",
    "Getir-": "Bring",
    "Gez-, Seyahat et-": "Travel",
    "Geziye çık-": "Go on an excursion",
    "Gir": "Get Into",
    "Git-": "Go",
    "Golf": "Golf",
    "Gönder-": "Send",
    "Gösteri, Göster-": "Show",
    "Güçlü": "Strong",
    "Gül-": "Laugh",
    "Gülümse-": "Smile",
    "Gün": "Day",
    "Güneş ışığı": "Sunlight",
    "Güneş yanığı ol-": "Get sunburnt",
    "Güvercin": "Pigeon",
    "Hafta": "Week",
    "Hala, Donuk Dur-": "Still",
    "Halk": "Public",
    "Hançer": "Dagger",
    "Hap": "Pill",
    "Harca-": "Spend",
    "Hareketsiz": "Sedentary",
    "Harika": "Great",
    "Hastalık": "Disease",
    "Hastane": "Hospital",
    "Hata": "Fault",
    "Hatırla": "Remember",
    "Hediye paketi": "Gift pack",
    "Hediye, Şu an": "Present",
    "Her şey": "Everything",
    "Her zaman": "Always",
    "Herhangi Bir Şey": "Anything",
    "Hisset-": "Feel",
    "Hizmet": "Service",
    "Hol": "Hall",
    "Huzurlu": "Peaceful",
    "Işık": "Light",
    "İçecek": "Beverage",
    "İçerik": "Content",
    "İfade et-": "Express",
    "İhtiyaç duy-": "Need",
    "İlaç": "Medicine",
    "İlişki": "Relationship",
    "İmza": "Signature",
    "İnsan anatomisi": "Human anatomy",
    "İnsanlık": "Humanity",
    "İnşa Et-": "Construct",
    "İnşaat": "Construction",
    "İsifa et-": "Resign",
    "İsim": "Name",
    "İste-": "Want",
    "İş, Çalış-": "Work",
    "İş": "Job",
    "İtiraf et-": "Admit",
    "İtiraz": "Objection",
    "İyi": "Good",
    "İyileş-": "Recover",
    "İz": "Scar",
    "İzin Ver-": "Let",
    "İzle-": "Watch",
    "Kafein": "Caffein",
    "Kal-": "Stay",
    "Kaldır-": "Lift",
    "Kamuoyu": "Public opinion",
    "Kandır-, Kopya çek-": "Cheat",
    "Kanıt-": "Prove",
    "Kapa-": "Turn off",
    "Kapalı Alan": "Closed Area",
    "Kapı": "Door",
    "Karakter": "Character",
    "Katkı": "Contribution",
    "Kayıt": "Recording",
    "Kebap": "Kebab",
    "Kendi(Erkek)": "Himself",
    "Kes-": "Cut Off",
    "Kese": "Pouch",
    "Kesin": "Definite",
    "Keyif al-": "Enjoy",
    "Kır-": "Break",
    "Kilo al-": "Put on weight",
    "Konforlu": "Comfortable",
    "Konuş-, Sohbet et-": "Talk",
    "Koru-": "Protect",
    "Koy-": "Put",
    "Kök hücre": "Stem cell",
    "Köşe": "Corner",
    "Kötü": "Bad",
    "Köy": "Village",
    "Kuraklık": "Drought",
    "Losyon": "Lotion",
    "Mahalle": "Town",
    "Makale": "Essay",
    "Mankenlik": "Modelling",
    "Merdiven": "Ladder",
    "Meydan": "Square",
    "Mezun Ol-": "Graduate",
    "Mide boz-": "Unsettle stomach",
    "Miktar": "Amount",
    "Mum": "Candle",
    "Müsteri": "Customer",
    "Müthiş": "Wonderful",
    "Oda": "Room",
    "Oku-": "Read",
    "Ofis işi": "Office job",
    "Okul": "School",
    "Olmazsa olmaz": "Indispensable",
    "Organizasyon": "Organize",
    "Otur-": "Sit",
    "Oturma odası": "Living room",
    "Oyna-": "Play",
    "Oy ver-": "Vote",
    "Oyun": "Game",
    "Oyunculuk": "Acting",
    "Öde-": "Pay",
    "Öğle Yemeği": "Lunch",
    "Öğren-": "Learn",
    "Öğrenciler": "Students",
    "Öğretim görevlisi": "Lecturer",
    "Ölüm": "Death",
    "Önceden": "Already",
    "Önemli": "Important",
    "Özle-, Kaçır-": "Miss",
    "Paket": "Package",
    "Para": "Money",
    "Pasaport": "Passport",
    "Pazartesi": "Monday",
    "Performans": "Performance",
    "Personel": "Staff",
    "Polis": "Policeman / Policewoman",
    "Promosyon al-": "Get a promotion",
    "Protestocu": "Protestor",
    "Raf": "Shelf",
    "Resepsiyonist": "Receptionist",
    "Roman": "Novel",
    "Saat, İzle-": "Watch",
    "Sabit": "Stable",
    "Saçma": "Ridiculous",
    "Sadece": "Just",
    "Sağlam": "Unbroken",
    "Saldırı": "Attack",
    "Sanatçı": "Artist",
    "Sar-, Paketle-": "Wrap",
    "Sat-": "Sell",
    "Satış Elemanı": "Salesperson",
    "Sayfa": "Page",
    "Seç-": "Elect",
    "Ses": "Voice",
    "Seslendir-": "Verbalize",
    "Seyahat Acentası": "Travel Agency",
    "Seyirci, İzleyici": "Audience",
    "Sıtma": "Malaria",
    "-Siz": "Without",
    "Sigara İç-": "Smoking",
    "Sistem": "System",
    "Sokak yasağı": "Curfew",
    "Sokak": "Street",
    "Son derece": "Extremely",
    "Son": "Last",
    "Sonraki saat": "Next hour",
    "Sömür-, Faydalan-": "Exploit",
    "Söyle-, Anlat-": "Tell",
    "Söyle-": "Say, Utter",
    "Stabilize Et-": "Stabilize",
    "Sunum": "Presentation",
    "Sürücü": "Driver",
    "Şalter, Düğme": "Switch",
    "Şarkı söyle-": "Sing",
    "Şarkı": "Song",
    "Şaşırt-": "Bewilder",
    "Şelale": "Waterfall",
    "Şey": "Thing",
    "Şikayetçi ol-": "Complain",
    "Şirket": "Company",
    "Şok, Şok ol-": "Shock",
    "Tail": "Holiday",
    "Tamir et-": "Repair",
    "Tarihi yer": "Historical Place",
    "Taş, Kaya, Salla-": "Rock",
    "Taşı-": "Carry",
    "Tazele-": "Refresh",
    "Tehtit et-": "Threaten",
    "Teklif": "Offer, Proposal",
    "Teknik Müdür": "Technical Manager",
    "Temizle-": "Clean",
    "Tepsi": "Tray",
    "Teslim Et-": "Deliver",
    "Test": "Test",
    "Teşekkür Et-": "Thank",
    "Toplantı": "Meeting",
    "Toplum": "Society",
    "Trafik cezası": "Traffic ticket",
    "Tur Rehberi": "Tour Guide",
    "Tur": "Tour",
    "Tuzak": "Trap",
    "Tüket-": "Consume",
    "Uçak bileti": "Plane ticket",
    "Ulus": "Nation",
    "Uluslararası": "International",
    "Unut-": "Forget",
    "Uygula-": "Apply",
    "Uygunsuzca": "Improperly",
    "Uyu-, Uyku": "Sleep",
    "Ücret": "Fee",
    "Üçüncü kat": "Third floor",
    "Üretici": "Producer",
    "Üstünde çalış-": "Work on",
    "Üzgün": "Upset",
    "Var-": "Arrive",
    "Veri, Data": "Data",
    "Vurgula-": "Emphasize",
    "Yağmur": "Rain",
    "Yakala-": "Catch",
    "Yaklaşım, Yaklaş-": "Approach",
    "Yalvar-": "Beg",
    "Yanlış, Hata": "Wrong",
    "Yap-": "Make",
    "Yarım": "Half",
    "Yasak, Yasakla-": "Forbid, Ban",
    "Yaşa-": "Live",
    "Yavaşla-, Yavaşlat-": "Slow down",
    "Yaz-": "Write",
    "Ye-": "Eat",
    "Yemek": "Food",
    "Yerleş-": "Settle In",
    "Yeterlik": "Efficiency",
    "Yıka-, Yıkan-": "Wash",
    "Yıldız": "Star",
    "Yol": "Road",
    "Yola Çık-": "Set off",
    "Yorgun": "Tired",
    "Yurtdışı": "Abroad",
    "Yüksek vergi": "High tax",
    "Zaman, Saat": "Time",
    "Zamanla": "In time",
    "Zarar ver-, Hasara sebep ol-": "Cause damage",
    "Zarif": "Graceful",
    "Zina": "Adulterous",
    "Zor, Sert": "Hard"
};
