
var turkceingilizce = {
    "acil": "urgent",
    "affetmek": "forgive",
    "ağız": "mouth",
    "ağlamak": "cry",
    "ağrı": "pain",
    "acı": "pain",
    "akıl": "mind",
    "aktif etmek": "activate",
    "alan": "space",
    "alet": "device",
    "alışkanlık": "habit",
    "altın gol": "golden goal",
    "Amerika": "the USA",
    "ani": "memory",
    "aniden": "suddenly",
    "anlamak": "understand",
    "anlaşma": "agreement",
    "anlatmak": "tell",
    "anlık": "momentary",
    "antik": "antique",
    "araba": "car",
    "asgari": "minimum",
    "asker": "soldier",
    "aşağılık kompleksi": "inferiority complex",
    "atlamak": "skip",
    "ayrılmak": "leave",
    "bakış açısı": "point of view",
    "başlangıç": "beginning",
    "belirsizlik": "uncertainty",
    "berbat": "awful",
    "bile": "even",
    "bilim adamı": "scientist",
    "bilmek": "know",
    "biraz": "a bit",
    "borç": "debt",
    "boşanmak": "divorce",
    "bölge": "area, region",
    "bulmak": "find",
    "buluşmak": "meet",
    "bürokrat": "bureaucrat",
    "bütçe": "budget",
    "cahil": "ignorence",
    "cennet": "paradise",
    "cesaret": "courage",
    "ciddi": "serious",
    "cihaz": "device",
    "çabuk bir şekilde": "quickly",
    "çalımlamak": "dribble",
    "çalmak": "steal",
    "çanta": "purse",
    "çatışma": "conflict",
    "çay": "tea",
    "çıkar": "interest",
    "çıkarmak": "enact(yasa)",
    "çocukluk": "childhood",
    "dal": "branch",
    "değişiklik": "change",
    "deli": "crazy,mad",
    "deneyim": "experience",
    "deprem": "earthquake",
    "detay": "detail",
    "dil": "language",
    "dile getirmek": "utter",
    "dolandırıcı": "swindler",
    "dolap": "wardrobe",
    "dönem": "term",
    "dönüştürmek": "transform",
    "duyurmak": "announce",
    "düşünmek": "think",
    "düşürmek": "pull down",
    "düzenleme": "regulation",
    "eklemek": "add",
    "engelli": "handicapped",
    "enteresan": "interesting",
    "erken": "early",
    "eş(erkek)": "husband",
    "ev arkadaşı": "homemate",
    "fark": "difference",
    "farketmek": "notice",
    "fatura": "invoice",
    "feda etmek": "sacrifice",
    "garip": "weird",
    "gazete": "newspaper",
    "gemi": "ship",
    "gerçek": "truth",
    "gereksiz": "unnecessary",
    "getirmek": "bring",
    "gezegen": "planet",
    "gol atmak": "score",
    "göndermek": "send",
    "görmezden gelmek": "ignore",
    "görünüşe göre": "apparently",
    "görüşme": "interview",
    "röportaj": "interview",
    "gündem": "agenda",
    "güvenilir": "reliable",
    "güzellik": "beauty",
    "haçlı seferi": "crusade",
    "hafta": "week",
    "hakem": "referee",
    "halk oylaması": "referendum",
    "hasar": "damage",
    "hastalık": "illness",
    "hata": "mistake",
    "hayat": "life(çoğul:lives)",
    "hazine haritası": "treasure map",
    "helper": "yardımcı",
    "henüz": "yet",
    "hızlı bir şekilde": "quickly",
    "hintli": "Indian",
    "ıssız": "desolate",
    "icat": "invention",
    "içecek": "beverage",
    "içermek": "contain",
    "içtima": "muster",
    "ikna etmek": "convince",
    "ilaç": "medicine",
    "ilk olarak": "firstly",
    "imza": "signature",
    "indirim": "sale",
    "inmek": "go down",
    "inşaat": "construction",
    "iptal etmek": "cancel",
    "İspanyol": "Spanish",
    "istihdam etmek": "employ",
    "İtalya": "Italy",
    "kabul etmek": "accept",
    "kaçınmak": "avoid",
    "kaçırmak": "smuggle",
    "kafein": "caffein(e)",
    "kahkaha": "laughter",
    "kaldırmak": "remove",
    "kaleci": "goal keeper",
    "kalıcı": "permanent",
    "kalite": "quality",
    "kalp": "heart",
    "kandırmak": "cheat",
    "kapatmak": "close",
    "kapkaççı": "snatcher",
    "kaptan": "captain",
    "karşılaşmak": "encounter",
    "katil zanlısı": "murder suspect",
    "kaydetmek": "save",
    "kayıp": "loss",
    "kaynak": "source",
    "kendini": "yourself",
    "kırmak": "break",
    "kısıtlama": "precaution",
    "kimlik": "identity",
    "kişisel": "personal",
    "klavye": "keyboard",
    "koku": "smell",
    "konaklama": "accommodation",
    "konu": "subject",
    "kovmak": "fire",
    "köhne": "ratty",
    "köprü": "bridge",
    "köşe": "corner",
    "kötü bir şekilde": "badly",
    "kronometre": "chronometer",
    "kullanıcı": "user",
    "kumar": "gamble",
    "kurul": "council",
    "kurye": "courier",
    "lastik": "tyre",
    "liste": "list",
    "maalesef": "unfortunately",
    "maaş": "salary",
    "mağdur": "victim",
    "malikhane": "mansion",
    "masum": "innocent",
    "memur": "officer",
    "mevsim": "season",
    "meydan": "avenue",
    "meydana gelmek": "happen",
    "mimar": "architect",
    "minicik": "tiny",
    "mobilya": "furnish",
    "müşteri": "customer",
    "nitelendirmek": "define",
    "nöbetçi kulübesi": "sentry box",
    "Orta Doğu": "Middle East",
    "otel": "hotel",
    "oyun": "game",
    "ödemek": "pay",
    "öfke": "rage",
    "öldürmek": "kill",
    "önemli": "important",
    "özel": "special",
    "özlü söz": "wise saying",
    "paket": "package",
    "paylaşmak": "share",
    "pek çok": "a lot of",
    "pembe dizi": "soap operas",
    "pencere": "window",
    "protesto": "protest",
    "psikolojik": "psychological",
    "rıhtım": "harbour",
    "liman": "harbour",
    "risk": "risk",
    "roman": "novel",
    "sabah": "morning",
    "saç teli": "barba",
    "sağlık": "health",
    "saldırı": "attack",
    "saptamak": "establish",
    "sarılmak": "hug",
    "satılığa çıkartmak": "put up",
    "satranç": "chess",
    "sayfa": "page",
    "seçmek": "choose",
    "sehpa": "tea table",
    "sekreter": "secretary",
    "sensör": "censor",
    "sipariş vermek": "order",
    "solungaç": "gill",
    "solunum yapmak": "respire",
    "son dakika": "last minute",
    "son zamanlarda": "recently",
    "son": "end,latest",
    "sonuç": "result",
    "sormak istemek": "ask",
    "sözde": "so-called",
    "sulamak": "water",
    "sürpriz": "surprise",
    "süt": "milk",
    "şey": "thing",
    "şöför": "driver",
    "tabak": "plate",
    "takım": "team",
    "takviye birlik": "reinforcing unit",
    "tamamen": "completely",
    "tasarlamak": "design",
    "tat": "taste",
    "tedavi": "cure",
    "tehlikeli": "dangerous",
    "teklif etmek": "offer",
    "teslim etmek": "deliver,submit",
    "tik": "twitch",
    "tutar": "amount",
    "meblağ": "amount",
    "uğursuzluk": "bad luck",
    "ulaşmak(teslim)": "reach",
    "uyarmak": "warn",
    "uygun": "proper",
    "uzay": "space",
    "uzun": "long",
    "ücret": "wage",
    "üçüncü": "third",
    "üretici": "producer",
    "üretmek": "make",
    "ürün": "product",
    "üye": "member",
    "vahşi": "wild",
    "vatandaş": "citizen",
    "veranda": "veranda",
    "virüs": "virus",
    "vücut": "body",
    "yaklaşım": "approach",
    "yalnız": "alone",
    "yanlış": "wrong",
    "yapmak": "make",
    "yaramazlık": "naughtiness",
    "yarar": "benefit",
    "yaratmak": "create",
    "oluşturmak": "create",
    "yasa": "law",
    "yasak": "ban",
    "yasal": "legal",
    "yaşam": "life",
    "yayın": "broadcasting",
    "yeni": "new",
    "yetenek": "ability",
    "yeterince": "enough",
    "yetersiz": "insufficient",
    "yıldız oyuncu": "star player",
    "yıldız": "star",
    "yıpratmak": "wear down",
    "yoğun bakım ünitesi": "intensive care unit",
    "yoğun": "intensive",
    "yolsuzluk": "corruption",
    "zannetmek": "suppose",
    "zehir": "poison",
    "zor": "hard"
};
