
var ingilizceturkce = {
    "accent": "aksan",
    "accidentally": "tesadüfen",
    "act": "oynamak",
    "actress": "aktris",
    "administrative": "yönetimsel",
    "affect": "etkilemek",
    "clean": "temizlemek",
    "clear": "açık",
    "click": "tık",
    "client": "müşteri",
    "close": "kapatmak",
    "cloud": "bulut",
    "agricultural": "tarımsal",
    "cold": "soğuk",
    "company": "şirket",
    "computer": "bilgisayar",
    "concert": "konser",
    "condition": "durum",
    "confidential": "gizli",
    "confirmation": "onay",
    "conscious": "bilinçli",
    "consent": "razı olmak",
    "consider": "düşünmek",
    "contract": "sözleşme",
    "cop": "polis",
    "cost efficient": "uygun maliyetli",
    "country director": "ülke direktörü",
    "country": "ülke",
    "course": "kurs",
    "cousin": "kuzen",
    "crisis": "kriz",
    "culture": "kültür",
    "curb": "engellemek",
    "cure": "tedavi",
    "customer": "müşteri",
    "dairy": "günlük",
    "damage": "hasar",
    "dance": "dans",
    "debate": "tartışma",
    "deceased": "rahmetli",
    "decision": "karar",
    "deep": "derin",
    "definite": "kesin",
    "demand": "istek, talep",
    "denigrate": "kötülemek",
    "destination": "hedef, varış",
    "detention camp": "toplama kampı",
    "device": "cihaz",
    "different": "farklı",
    "difficult": "zor",
    "discover": "keşfetmek",
    "disaster": "felaket",
    "dismissal": "kovulma",
    "district": "bölge",
    "divorcement": "boşanma",
    "document": "belge",
    "door": "kapı",
    "draw": "çekmek",
    "dwarf": "cüce",
    "each other": "birbirlerini",
    "early": "erken",
    "earthquake": "deprem",
    "easy": "kolay",
    "emotional": "duygusal",
    "emporer": "imparator",
    "empty": "boş",
    "every": "her",
    "everybody": "herkes",
    "exercise": "egzersiz, aktivite",
    "eyes": "gözler",
    "fabric": "bez",
    "facility": "tesis",
    "famous": "ünlü",
    "fault": "hata",
    "field": "tarla",
    "file": "dosya",
    "final": "son",
    "financial": "finansal",
    "finding": "bulgu",
    "first": "ilk",
    "fisherman": "balıkçı",
    "floor": "yer, pist",
    "flower": "çiçek",
    "flu": "grip",
    "frantic": "telaşlı",
    "friend": "arkadaş",
    "game": "oyun",
    "garden": "bahçe",
    "girl": "kız",
    "girlfriend": "kız arkadaş",
    "go": "gitmek",
    "government": "hükümet",
    "graduation": "mezuniyet",
    "grandfather": "dede",
    "grandparents": "büyükanne&baba",
    "great": "büyük",
    "green": "yeşil",
    "ground": "yer",
    "grow": "büyümek",
    "guest": "konuk, misafir",
    "habit": "alışkanlık",
    "hall": "salon",
    "hallow": "oyuk",
    "hand": "el",
    "harmful": "zararlı",
    "heart": "kalp",
    "heavy": "yoğun",
    "help": "yardım",
    "hereditary": "kalıtsal",
    "high": "yüksek",
    "highly": "yüksek derecede",
    "history": "tarih",
    "holy": "kutsal",
    "homeless": "evsiz",
    "hope": "umut",
    "horse": "at",
    "hose": "hortum",
    "hostage": "rehine",
    "hour": "saat",
    "husband": "eş (erkek)",
    "ill": "hasta",
    "imitation": "taklit",
    "important": "önemli",
    "improve": "gelişmek",
    "incubator": "küvöz",
    "intensive": "yoğun",
    "interpret": "yorumlamak",
    "intelligence": "zeka",
    "investment": "yatırım",
    "invite": "davet etmek",
    "island": "ada",
    "issue": "konu",
    "jockey": "jokey",
    "keep": "saklamak",
    "kid": "çocuk",
    "kind": "kibar, tür",
    "know": "bilmek",
    "lane": "şerit",
    "language": "dil",
    "last": "son",
    "lawsuit": "dava",
    "lawyer": "avukat",
    "learn": "öğrenmek",
    "leave": "ayrılmak, terketmek",
    "lesson": "ders",
    "license": "lisans, belge",
    "life": "hayat",
    "light": "ışık",
    "like": "gibi",
    "listening": "dinleme",
    "little": "küçük",
    "live": "canlı",
    "lobby": "lobi",
    "lonely": "yalnız",
    "long": "uzun",
    "look": "görünmek",
    "lover": "aşık",
    "management": "yönetim",
    "manager": "müdür",
    "manner": "davranış",
    "many": "birçok",
    "married": "evli",
    "masterful": "usta",
    "measure": "ölçü",
    "medicine": "ilaç",
    "meeting": "toplantı",
    "member": "üye",
    "method": "metod",
    "middleclass": "orta sınıf",
    "midnight": "geceyarısı",
    "minority": "azınlık",
    "minute": "dakika",
    "mission": "görev",
    "mistake": "hata",
    "mobile": "mobil",
    "monster": "canavar",
    "month": "ay",
    "mountain": "dağ",
    "municipality": "belediye",
    "nanny": "dadı",
    "nation": "millet",
    "national": "milli",
    "nature": "doğa",
    "need": "ihtiyaç",
    "neighborhood": "mahalle",
    "neutralize": "etkisiz hale getirmek",
    "never": "asla",
    "new": "yeni",
    "next": "gelecek",
    "night": "gece",
    "nightmare": "kabus",
    "nomadic": "göçebe",
    "notice": "farketmek",
    "novel": "roman",
    "obstacle": "engel",
    "occasional": "ara sıra olan",
    "official": "resmi",
    "officially": "resmen",
    "old": "yaşlı",
    "once": "bir keresinde/bir kez",
    "online": "çevrim içi",
    "operation": "operasyon",
    "opposition": "muhalefet",
    "organization": "organizasyon",
    "other": "diğer",
    "ottoman": "osmanlı",
    "owner": "sahip",
    "panic": "panik",
    "paradise": "cennet",
    "paraglide": "paraşütle atlamak",
    "parent": "ebeveyn",
    "parliament": "parlamento",
    "people": "insanlar",
    "permission": "izin",
    "personal": "kişisel",
    "pesticide": "ilaç (böcek, haşere)",
    "petition": "dilekçe",
    "pharmacy": "eczane",
    "phone": "telefon",
    "physical": "fiziksel",
    "plane": "uçak",
    "planet": "gezegen",
    "plant": "bitki",
    "play": "çalmak",
    "pocket": "cep",
    "poem": "şiir",
    "police station": "karakol",
    "policeman": "polis",
    "politician": "politikacı",
    "practice": "egzersiz",
    "pregnant": "hamile",
    "prescription": "reçete",
    "presenter": "sunucu",
    "president": "başkan",
    "prize": "ödül",
    "problem": "problem",
    "produce": "üretmek",
    "product": "ürün",
    "project": "proje",
    "proper": "düzgün",
    "provide": "sağlamak",
    "punish": "cezalandırmak",
    "put": "koymak",
    "race": "yarış",
    "raid": "baskın",
    "rain": "yağmur",
    "rapid": "hızlı",
    "ready": "hazır",
    "real": "gerçek",
    "reason": "neden",
    "recent": "son",
    "red": "kırmızı",
    "referee": "hakem",
    "regular": "düzenli",
    "rehearsal": "prova",
    "reject": "geri çevirmek",
    "repairman": "tamirci",
    "report": "rapor",
    "request": "istemek",
    "result": "sonuç",
    "room": "oda",
    "roommate": "oda arkadaşı",
    "rose": "gül",
    "safety": "güvenlik",
    "same": "aynı",
    "satirical": "alaycı",
    "saturday": "cumartesi",
    "say": "söylemek, demek",
    "scare": "korkutmak",
    "school": "okul",
    "scientist": "bilim insanı",
    "sea side": "deniz kenarı",
    "season": "mevsim",
    "seat": "yer",
    "secret": "sir",
    "see": "görmek",
    "send": "göndermek",
    "servant": "hizmetçi",
    "session": "oturum",
    "severe": "şiddetli",
    "shape": "şekil",
    "shoe": "ayakkabı",
    "short": "kısa",
    "show": "göstermek",
    "silent": "sakin",
    "similar": "benzer",
    "sing": "söylemek",
    "singer": "şarkıcı",
    "sister": "kız kardeş",
    "sit": "oturmak",
    "situation": "durum",
    "skill": "beceri",
    "slow": "yavaş",
    "small": "küçük",
    "smile": "gülümsemek",
    "smiling": "gülümse-y-en",
    "society": "toplum",
    "soil": "toprak",
    "soldier": "asker",
    "some": "bazı",
    "song": "şarkı",
    "speaking": "konuşma",
    "special": "özel",
    "sportsman": "sporcu",
    "stage": "sahne",
    "state": "eyelet",
    "stay": "kalmak",
    "stick": "sopa",
    "still": "hala",
    "stone": "taş",
    "stormy": "fırtınalı",
    "story": "hikaye",
    "strengthen": "güçlendirmek",
    "strict": "katı",
    "strong": "güçlü",
    "structure": "yapı",
    "student": "öğrenci",
    "success": "başarı",
    "successful": "başarılı",
    "sudden": "ani",
    "summer": "yaz",
    "sundays": "pazarları",
    "supplier": "tedarikçi",
    "surface": "yüzey",
    "surgery": "ameliyat",
    "swiss": "isviçreli",
    "table": "masa",
    "take": "almak (ders)",
    "talk": "konuşmak",
    "tea": "çay",
    "teach": "öğretmek",
    "teacher": "öğretmen",
    "team": "takım, ekip",
    "tell": "anlatmak",
    "terminate": "son vermek",
    "the whole": "bütün",
    "thing": "şey",
    "time": "zaman",
    "today": "bugün",
    "tomorrow": "yarın",
    "topic": "konu",
    "tough": "zorlu",
    "trade": "ticaret",
    "transform": "dönüştürmek",
    "tribe": "kavim",
    "tribune": "tribün",
    "turkish people": "türkler",
    "type": "tür",
    "unity": "birlik",
    "university": "üniversite",
    "updated": "güncel",
    "upgraded": "güncel",
    "urgent": "acil",
    "use": "kullanım",
    "vaccine": "aşı",
    "visitor": "ziyaretçi",
    "vital": "önemli",
    "voice": "ses",
    "volunteer": "gönüllü",
    "wall": "duvar",
    "wallet": "cüzdan",
    "warm": "sıcak",
    "warn": "uyarmak",
    "warning": "uyarı",
    "water": "sulamak",
    "waterpipe": "nargile",
    "way": "şekil",
    "weather": "hava",
    "week": "hafta",
    "whistle": "düdük",
    "whole": "bütün",
    "window": "pencere",
    "woman": "kadın",
    "world": "dünya",
    "wrong": "yanlış",
    "year": "yıl",
    "yellow": "sarı",
    "young": "genç",
    "youngster": "genç, delikanlı",
    "yesterday": "dün"
};
