
var ingilizceturkce = {
    "accelerate": "hızlandırmak",
    "accept": "kabul etmek",
    "acrobat": "akrobat",
    "adaptation": "uyum",
    "add": "eklemek",
    "admiration": "hayranlık",
    "adopt": "evlat edinmek",
    "advanced level": "ileri seviye",
    "advertisement": "reklam",
    "aegean": "ege",
    "after": "-nın peşinden, -den sonra",
    "aggressive": "agresif",
    "agree": "hemfikir ol-",
    "ancient era": "eski çağ",
    "answer": "cevap",
    "applicant": "aday",
    "apply": "uygulamak",
    "area": "bölge",
    "arrangement": "düzenleme",
    "artifical": "yapay",
    "Atlantic Ocean": "Atlas Okyanusu",
    "attack": "saldırmak",
    "attribute": "yüklemek, atfetmek",
    "audience": "seyirci",
    "authorities": "yetkililer",
    "avoid": "-den kaçınmak",
    "away from": "-den uzak",
    "bake": "pişirmek",
    "balcony": "balkon",
    "bay": "koy",
    "bazaar": "pazar",
    "become": "olmak",
    "believe": "inanmak",
    "birthmark": "doğum lekesi",
    "bleeding": "kanama",
    "blood": "kan",
    "boat": "tekne",
    "bone": "kemik",
    "bosphorus": "boğaz",
    "Brazil": "Brezilya",
    "bridge": "köprü",
    "burn": "yakmak",
    "call": "çağrı",
    "cancel": "iptal etmek",
    "candidate": "aday",
    "carry": "taşımak",
    "change": "değiştirmek",
    "childhood": "çocukluk",
    "church": "kilise",
    "circus": "sirk",
    "coffee table": "sehpa",
    "colonel": "albay",
    "commercial": "(TV/radyo) reklam",
    "communication": "iletişim",
    "compensation": "tazminat",
    "competition": "yarışma",
    "confirm": "onaylamak",
    "consensus": "oy birliği",
    "consider": "düşünmek",
    "considerable": "hatrı sayılır",
    "construction": "inşaat",
    "continent": "kita",
    "convince": "ikna etmek",
    "cop": "polis",
    "couple": "çift",
    "courage": "cesaret",
    "court": "mahkeme",
    "crocodile": "timsah",
    "customer": "müşteri",
    "dangerous": "tehlikeli",
    "daughter": "kız çocuğu",
    "death": "ölüm",
    "decade": "10 yıl",
    "declaration": "ilan",
    "delegate": "temsilci/delege",
    "demonstration": "gösteri",
    "Denmark": "danimarka",
    "deputy": "milletvekili",
    "destroy": "yıkılmak",
    "dial": "tuşlamak",
    "different": "farklı",
    "diligent": "marifetli",
    "direct": "yönetmek",
    "director": "müdür",
    "discuss": "tartışmak",
    "dispose": "atmak",
    "divorce": "boşanmak",
    "domestic": "yerli",
    "door": "kapı",
    "doorman": "kapıcı",
    "drawn": "çekmek (dikkat/tepki)",
    "dynasty": "hanedan",
    "each": "her",
    "Earthquake victim": "depremzede",
    "effort": "çaba",
    "effuse": "taşırmak",
    "elect": "seçmek",
    "elected": "seçilen (seçilmiş)",
    "employ": "işe almak",
    "encolour": "renklendirmek",
    "energy source": "enerji kaynağı",
    "enlighten": "aydınlatmak",
    "enormous": "muazzam",
    "enroll": "kayıt olmak",
    "error": "hata",
    "evidence": "kanıt",
    "exaggerate": "abartmak",
    "execution": "idam",
    "exile": "sürgün etmek",
    "existance": "varlık",
    "expect": "ummak",
    "failing": "başarısızlık",
    "famous": "ünlü",
    "fantastic": "muhteşem, harika",
    "far away": "çok uzak/ çok uzakta",
    "fascinate": "hayran bırakmak",
    "favourite": "favori",
    "few": "bir kaç",
    "field": "tarla",
    "fire": "kovmak",
    "first": "ilk",
    "following": "takip eden (önümüzdeki)",
    "for a while": "bir süre",
    "force": "güç",
    "foreigner": "yabancı",
    "forensic finding": "adli bulgu",
    "forest": "orman",
    "format": "biçimlendirmek",
    "foundation": "kuruluş",
    "France": "Fransa",
    "friday": "cuma",
    "frog": "kurbağa",
    "gift": "hediye",
    "give": "vermek",
    "glass": "bardak",
    "gossip": "dedikodu",
    "governor": "vali",
    "hang": "asmak",
    "have": "(sıkıntı) çekmek/sahip olmak",
    "healthcare": "sağlık hizmeti",
    "hear": "duymak",
    "heart attack": "kalp krizi",
    "heart": "kalp",
    "hen party": "bekarlığa veda partisi (kadın)",
    "high-tech": "yüksek teknoloji",
    "highway": "otoban",
    "hire": "işe almak",
    "hold": "tutmak, düzenlemek",
    "huge": "büyük",
    "ill": "hasta",
    "immigrant": "göçmen",
    "importance": "önem",
    "impress": "etkilemek",
    "in spite of": "-e rağmen",
    "incident": "olay",
    "index finger": "işaret parmağı",
    "injured": "yaralı",
    "ink": "mürekkep",
    "innovation": "yenilik",
    "inseparable": "ayrılmaz",
    "instructor": "eğitmen",
    "island": "ada",
    "judge": "hakim",
    "kill": "öldürmek",
    "knee": "diz",
    "knife": "bıçak",
    "know": "bilmek",
    "lake": "göl",
    "last": "son",
    "law": "kanun",
    "leave": "terk etmek, -den ayrılmak",
    "librarian": "kütüphane memuru",
    "life space": "yaşam alanı",
    "link": "birleştirmek",
    "lobby": "lobi",
    "local": "yerel",
    "lock": "kilitlemek",
    "maid": "hizmetçi",
    "main news bulletin": "ana haber bülteni",
    "married": "evli",
    "matter": "madde",
    "meaning": "anlam",
    "medicine": "ilaç",
    "membership": "üyelik",
    "metal": "metal",
    "midnight": "gece yarısı",
    "model": "model",
    "more": "daha fazla",
    "move": "taşınmak",
    "musician": "müzisyen",
    "muster-roll": "askeri personel listesi",
    "need": "ihtiyaç duymak",
    "new year eve": "yılbaşı arifesi",
    "notice": "farketmek",
    "ocean": "okyanus",
    "offer": "teklif",
    "olympic": "olimpiyat",
    "operator": "operatör",
    "opportunity": "fırsat",
    "order": "emretmek, sipariş vermek",
    "orphan": "yetim",
    "outstanding": "göz alıcı",
    "owner": "sahip",
    "pain": "acı",
    "paint": "boyamak",
    "paper": "kağıt",
    "parcel": "koli",
    "part": "kısım",
    "Pasific Ocean": "Pasifik Okyanusu",
    "passenger": "yolcu",
    "patient": "hasta",
    "patty": "börek",
    "perform": "performans sergilemek",
    "personnel": "eleman-elemanlar",
    "pharmacy": "eczane",
    "pianist": "piyanist",
    "pick": "koparmak (topla-)",
    "planet": "gezegen",
    "precaution": "önlem",
    "prefer": "tercih etmek",
    "president": "cumhurbaşkanı",
    "press conference": "basın toplantısı",
    "pressure": "baskı",
    "prevent": "önlemek",
    "priceless": "paha biçilemez",
    "prison": "hapishane",
    "process": "süreç",
    "produce": "üretmek",
    "property": "mülk",
    "prove": "kanıtlamak",
    "province": "eyalet",
    "public": "halk",
    "publish date": "yayın tarihi",
    "pump": "pompalamak",
    "punish": "cezalandırmak",
    "purchase": "satın almak",
    "put up for sale": "satışa sunmak",
    "quantity": "miktar",
    "radical": "köklü, radikal",
    "reach": "-e ulaşmak",
    "reaction": "tepki",
    "reason": "sebep",
    "region": "bölge",
    "regular": "düzenli",
    "reject": "reddetmek",
    "relative": "akraba",
    "reliable": "güvenilir",
    "reply": "cevaplamak",
    "republic": "cumhuriyet",
    "research": "araştırma(k)",
    "regularly": "düzenli olarak",
    "relationship": "ilişki",
    "responsible (for)": "(-den) sorumlu",
    "reveal": "ifşa etmek",
    "reward": "ödül",
    "river": "nehir",
    "rob": "soymak",
    "rumour": "söylenti",
    "run": "koşmak",
    "safe": "kasa",
    "satellite": "uydu",
    "scan": "taramak",
    "science-fiction": "bilim kurgu",
    "sea": "deniz",
    "second": "saniye",
    "security guard": "güvenlik görevlisi",
    "see": "görmek",
    "select": "seçmek",
    "sell": "satmak",
    "sentence": "mahkum etmek",
    "serial": "seri",
    "shelf": "raf",
    "ship": "gemi",
    "silently": "sessiz bir şekilde",
    "slily": "sinsice/çaktırmadan",
    "snack": "ara öğün",
    "software": "yazılım",
    "souvenir": "hediyelik eşya",
    "space engineer": "uzay mühendisi",
    "special": "özel",
    "speech": "konuşma, söylev",
    "spend": "harcamak",
    "sponsor": "destek sağlamak",
    "square": "meydan",
    "stand": "dikilmek",
    "statue": "heykel",
    "steal": "çalmak",
    "step": "adım",
    "strict": "katı",
    "sunflower": "ayçiçek",
    "take": "almak",
    "take care of": "ile ilgilenmek",
    "tale": "hikaye",
    "terminate": "yok etmek, son vermek",
    "theatre": "tiyatro",
    "think": "düşünmek",
    "through": "aracılığı ile",
    "thumb": "baş parmak",
    "tiny": "küçük/minik",
    "tomorrow": "yarın",
    "too much": "çok fazla",
    "traffic jam": "trafik sıkışıklığı",
    "trainer": "eğitmen",
    "translate": "çevirmek",
    "travel": "seyahat etmek",
    "tribe": "kabile",
    "underline": "alt(ını) çiz",
    "until now / so far": "şimdiye kadar",
    "untold": "anlatılmamış",
    "vandalism": "barbarlık",
    "various": "çeşitli",
    "verify": "teyit etmek, doğrulamak",
    "village": "köy",
    "virtue": "erdem",
    "visit": "ziyaret etmek",
    "wait": "beklemek",
    "waiting room": "bekleme odası",
    "wardrobe": "gardrop",
    "waste": "atık",
    "watch": "izlemek",
    "with the help of": ".. nın yardımıyla",
    "within": "içerisinde",
    "word": "söz",
    "wrestle": "güreşmek",
    "write": "yazmak",
    "zoo": "hayvanat bahçesi"
};
