
var soruvekelimeler = {
    "29UygulamaEn": {
        "soru1": "It is a tale about a frog.",
        "kelimeler1": "(tale: masal/about: ile ilgili (hakkında) / frog: kurbağa)",
        "soru2": "The river links the two cities there.",
        "kelimeler2": "(river: nehir/ link: birleştir-)",
        "soru3": "There, a crocodile is in the lake.",
        "kelimeler3": "(crocodile: timsah/lake: göl)",
        "soru4": "There is a village far away.",
        "kelimeler4": "(village: köy/far away: çok uzak/ çok uzakta)",
        "soru5": "A ship is there in the sea.",
        "kelimeler5": "(ship: gemi/ sea: deniz)",
        "soru6": "The pilgrims in the sightseeing bus are from Germany.",
        "kelimeler6": "(sightseeing bus: tur otobüsü / pilgrim: hacı)",
        "soru7": "Here are tourists from France.",
        "kelimeler7": "(France: Fransa)",
        "soru8": "The instructors here are from Denmark.",
        "kelimeler8": "(instructor: eğitmen/ Denmark: Danimarka)",
        "soru9": "There will be a man standing at the door.",
        "kelimeler9": "(stand: dikil-/door: kapı)",
        "soru10": "There should be a maid in the hen party.",
        "kelimeler10": "(maid: hizmetçi/hen party: bekarlığa veda partisi (kadınların))"
    },
    "29UygulamaTr": {
        "soru1": "Bu ormanda vahşi hayvanlar var.",
        "kelimeler1": "(forest/wild/animal)",
        "soru2": "Aklımda deli sorular var.",
        "kelimeler2": "(mind/crazy/question)",
        "soru3": "Ev arkadaşımın özel bir yeteneği var.",
        "kelimeler3": "(homemate/special/ability)",
        "soru4": "Bu köşkte bir uğursuzluk var.",
        "kelimeler4": "(mansion/bad luck)",
        "soru5": "Lastikte delik var.",
        "kelimeler5": "(tyre / hole)",
        "soru6": "Şoförün enteresan bir tiki var.",
        "kelimeler6": "(driver/interesting/ twitch)",
        "soru7": "Çayda garip bir koku var.",
        "kelimeler7": "(tea/weird/smell)",
        "soru8": "Bu balkonda şen kahkahalarımız vardı.",
        "kelimeler8": "(balcony/happy/laughter)",
        "soru9": "Türkiye'de şu anda ekonomik belirsizlik var.",
        "kelimeler9": "(uncertainty)",
        "soru10": "Halının altında hazine haritası var.",
        "kelimeler10": "(carpet/treasure map)"
    },
    "30UygulamaEn": {
        "soru1": "Here has been this statue at the square for 50 years.",
        "kelimeler1": "(statue: heykel/ square: meydan)",
        "soru2": "There are dragon trainers in the movies about ancient eras.",
        "kelimeler2": "(dragon: ejderha/trainer. eğitmen/ancient era: eski çağ)",
        "soru3": "Everybody has a friend or a relative in Germany.",
        "kelimeler3": "(relative: akraba)",
        "soru4": "I have a pain in my heart because of love.",
        "kelimeler4": "(pain: acı/heart:kalp)",
        "soru5": "Ronaldo has an island in Atlantic Ocean.",
        "kelimeler5": "(island: ada/ocean: okyanus)",
        "soru6": "I have a birthmark on my knee.",
        "kelimeler6": "(birthmark: doğum lekesi/knee: diz)",
        "soru7": "According to the researches, there are some tribes living away from technology.",
        "kelimeler7": "(research: araştırma/tribe: kabile/ away from: -den uzak)",
        "soru8": "There is a tiny error in the software.",
        "kelimeler8": "(tiny: minik/error: hata/software: yazılım)",
        "soru9": "In October 29th, there was a demonstration about the declaration of Republic of Turkey on Bosphorus Bridge.",
        "kelimeler9": "(demonstration: gösteri / about: ile ilgili / declaration: ilan / Republic: Cumhuriyet/ Bosphorus: boğaz/bridge: köprü)",
        "soru10": "Here are many immigrants from Syria and Iraq.",
        "kelimeler10": "(immigrant: göçmen)"
    },
    "30UygulamaTr": {
        "soru1": "Listede önemli bir şahsın adı var.",
        "kelimeler1": "(list/important / name)",
        "soru2": "Bu arabanın park sensörü var.",
        "kelimeler2": "(car/censor)",
        "soru3": "Ağzımızın hiç tadı yok.",
        "kelimeler3": "(mouth/any/taste)",
        "soru4": "Kaptanımızın sizler için bir sürprizi var.",
        "kelimeler4": "(captain/surprise)",
        "soru5": "Hintli bürokratlarda aşağılık kompleksi var.",
        "kelimeler5": "(bureaucrat/inferiority/complex)",
        "soru6": "Hayatımda bir kedi bile yok.",
        "kelimeler6": "(cat/even)",
        "soru7": "İki takım arasında kalite farkı var.",
        "kelimeler7": "(team/quality/difference)",
        "soru8": "Kahvenin sağlık için pek çok yararı var.",
        "kelimeler8": "(coffee/health/ a lot of/benefit)",
        "soru9": "Bilgisayarımda tehlikeli bir virüs var.",
        "kelimeler9": "(computer/dangerous /virus)",
        "soru10": "Bu saatin benim için hatırası var.",
        "kelimeler10": "(watch/memory)"
    },
    "31UygulamaEn": {
        "soru1": "Arrangements will be made tomorrow.",
        "kelimeler1": "(arrangement: düzenleme/tomorrow: yarın)",
        "soru2": "This reward should have been given to him.",
        "kelimeler2": "(reward: ödül)",
        "soru3": "The president was elected in a cold January morning.",
        "kelimeler3": "(elect: seç-/president: cumhurbaşkanı)",
        "soru4": "Waste materials are disposed with various ways.",
        "kelimeler4": "(dispose:at/waste: atık/various: çeşitli)",
        "soru5": "I would never have expected to be watching a tennis match. But here I am.",
        "kelimeler5": "(expect: um-, watch: izle-)",
        "soru6": "The fire in California has burned the city forests.",
        "kelimeler6": "(burn: yak/forest: orman)",
        "soru7": "A three-year-old girl has walked with the help of the assistant dog.",
        "kelimeler7": "(with the help of: .. nın yardımıyla)",
        "soru8": "Your friend, Martin has got a fantastic life.",
        "kelimeler8": "(fantastic: muhteşem,harika)",
        "soru9": "There are many fantastic bays to swim in Aegean region.",
        "kelimeler9": "(fantastic: harika / bay: koy/Aegean: Ege / region: bölge)",
        "soru10": "My relatives have got sunflower fields in the village.",
        "kelimeler10": "(sunflower: ayçiçek / field: tarla)"
    },
    "31UygulamaTr": {
        "soru1": "Şu sıralar, gündemimizde engelli vatandaşlar var.",
        "kelimeler1": "(recently/agenda/handicapped/citizen)",
        "soru2": "'Cahil cesareti' bilim insanları tarafından psikolojik bir hastalık olarak nitelendiriliyor.",
        "kelimeler2": "(ignorence/courage/scientist/illness/psychological/define)",
        "soru3": "Puzzle yapmak için kendine boş zaman yaratabilirsin.",
        "kelimeler3": "(make/yourself/free/time/create)",
        "soru4": "Görünüşe göre, halk oylaması yapmak için planlarda acil bir değişiklik isteniyor.",
        "kelimeler4": "(Apparently/hold a referendum/plan/urgent/change/ask)",
        "soru5": "İlk olarak, asgari ücret ile ilgili bazı yasal düzenlemeler yapılmalı.",
        "kelimeler5": "(firstly/minimum/wage/legal/regulation/make)",
        "soru6": "Haçlı seferlerinden bu yana, Osmanlı İmparatorluğu zor günler yaşamış.",
        "kelimeler6": "(crusade / experience/Ottoman Empire)",
        "soru7": "Yetersiz maaşlardan dolayı, bugün memurlar Bakırköy Meydan'ında eylem yaptı.",
        "kelimeler7": "(insufficient/salary/officer/square/protest/make)",
        "soru8": "Başbakan geçen akşam televizyonda çok önemli bir mesaj verdi.",
        "kelimeler8": "(prime minister/last/evening/important/message/give-gave)",
        "soru9": "Beşiktaş, yıldız oyuncunun transferine bütçe yaratmak için Vodafone ile sponsorluk anlaşması imzaladı.",
        "kelimeler9": "(star player/budget/create/agreement/sponsorship)",
        "soru10": "Bu koltuk özel bir kumaş ile kaplanacak.",
        "kelimeler10": "(armchair/special/fabric/cover)"
    },
    "32UygulamaEn": {
        "soru1": "This virus must have been terminated till the end of this year.",
        "kelimeler1": "(terminate: yok et-)",
        "soru2": "Your documents might have been confirmed by the visa officer.",
        "kelimeler2": "(confirm: onayla-)",
        "soru3": "You should have added some salt before baking the patty.",
        "kelimeler3": "(add: ekle-/bake: pişir-/ patty: börek)",
        "soru4": "The police station has been attacked in spite of having high-tech cameras.",
        "kelimeler4": "(attack: saldır-/in spite of: e rağmen/ high-tech: yüksek teknoloji)",
        "soru5": "After discussing for a while, the married couple agreed on the same villa having 3 bathrooms.",
        "kelimeler5": "(discuss: tartış-/ for a while: bir süre / married: evli / agree: hemfikir ol-/bathroom:banyo)",
        "soru6": "The government could have taken strict precautions against coronavirus by applying some restrictions.",
        "kelimeler6": "(strict: katı/precaution: önlem/apply: uygula-/restriction: kısıtlama)",
        "soru7": "I have attributed too much meaning to this souvenir.",
        "kelimeler7": "(attribute: yükle-atfet-/too much: çok fazla/ meaning: anlam/ souvenir: hediyelik eşya)",
        "soru8": "You should have the courage to talk.",
        "kelimeler8": "(courage: cesaret)",
        "soru9": "Governor has got a great opportunity in spite of the gossips about him.",
        "kelimeler9": "(governor: vali/opportunity: fırsat/ in spite of e ragmen/gossip: dedikodu)",
        "soru10": "The detective has found a new evidence.",
        "kelimeler10": "(evidence:kanıt)"
    },
    "32UygulamaTr": {
        "soru1": "Çalışırken toplantılarda fikirlerimizi paylaşıyorduk.",
        "kelimeler1": "(meeting/idea/share)",
        "soru2": "Bu mevsimde dallarda çiçek göremez miyiz?",
        "kelimeler2": "(season/branch/flower)",
        "soru3": "Bir klavyenin kalitesi önemli değil miydi?",
        "kelimeler3": "(keyboard/quality)",
        "soru4": "Kobani'de etnik gruplar arasında çatışma meydana gelmişti.",
        "kelimeler4": "(between/conflict/happen)",
        "soru5": "O köyde masum çocukluğumu bıraktım.",
        "kelimeler5": "(village/innocent/childhood/leave)",
        "soru6": "Ürünleri İtalya'ya gemiler vasıtası ile kolayca kaçırabilirdik.",
        "kelimeler6": "(ship/via/Italy/smuggle)",
        "soru7": "Mimarınız projeyi 3 gün içinde teslim edecekti.",
        "kelimeler7": "(architect/submit)",
        "soru8": "İnsanlar bu bölgede onu Kerpeten Ali olarak tanır.",
        "kelimeler8": "(region/know)",
        "soru9": "Bu ilaç, uzun vadede vücudunda ciddi ve kalıcı hasarlar yaratabilir.",
        "kelimeler9": "(medicine/ in the long term/body/serious/permanent/damage/create)",
        "soru10": "Bir anlık öfkeyle kalbini kırabilirdim.",
        "kelimeler10": "(momentary/rage/heart/break)"
    }
}
