
var soruvekelimeler = {
    "05UygulamaTr": {
        "soru1": "Bu ayı neredeyse bitiririz.",
        "kelimeler1": "(month/near-ly/finish)",
        "soru2": "Bu akşamı çadırda geçirmek zorundayız.",
        "kelimeler2": "(evening/tent/spend)",
        "soru3": "Elleri çiçek gibi kokuyor.",
        "kelimeler3": "(smell/like/flowers)",
        "soru4": "Ligde kaderimizi bu maç belirler.",
        "kelimeler4": "(league/destiny/match/determine)",
        "soru5": "Sihirbaz büyüleyici bir şov hazırladı.",
        "kelimeler5": "(wizard/fascinating/prepare)",
        "soru6": "Fabrika içerisinde dikkatli (ce) yürümelisiniz.",
        "kelimeler6": "(factory/careful-/walk)",
        "soru7": "Kötü hava şartlarından dolayı bu hafta dersleri iptal ettik.",
        "kelimeler7": "(weather/condition/week/lecture/cancel)",
        "soru8": "Telefon numaramı kartımdan okuyabilirsiniz.",
        "kelimeler8": "(phone/number/card/read)",
        "soru9": "Arkadaşlarıma acı gerçeği söylemek zorundayım.",
        "kelimeler9": "(friend/sad/truth/tell)",
        "soru10": "Bu değerli ödülü annem için kazansa iyi olur.",
        "kelimeler10": "(precious/prize/mother/win)"
    },
    "05UygulamaEn": {
        "soru1": "The new nanny did tell a good story to the parents about child care.",
        "kelimeler1": "(nany:dadı/tell:anlat-/story:hikaye/parent:ebeveyn/child:çocuk/care:bakım)",
        "soru2": "You can help her during the seminar tomorrow.",
        "kelimeler2": "(help:yardım et-/tomorrow:yarın)",
        "soru3": "The team members should read this book every week.",
        "kelimeler3": "(team:takım/member:üye/week:hafta)",
        "soru4": "I have to stay with my friends at home because of the heavy rain.",
        "kelimeler4": "(stay:kal-/friend:arkadaş/heavy:yoğun/rain:yağmur)",
        "soru5": "The director did call the whole team for an urgent meeting yesterday.",
        "kelimeler5": "(director:yönetici/call:çağır-/whole:bütün/urgent:acil/meeting:toplantı/yesterday:dün)",
        "soru6": "This method can teach 7 languages to everyone in 3 months.",
        "kelimeler6": "(teach:öğret-/language:dil/everyone:herkes/month:ay)",
        "soru7": "The presenter did slowly give the microphone to the famous singer.",
        "kelimeler7": "(presenter:sunucu/slow-:yavaş/famous:ünlü/singer:şarkıcı)",
        "soru8": "Best friends should keep their secrets in all situations.",
        "kelimeler8": "(best:(en) iyi/keep:sakla-/secret:sır/all:her/situation:durum)",
        "soru9": "Cem Yılmaz did masterfully play his role as a policeman in Av Mevsimi.",
        "kelimeler9": "(masterful-:usta/play:oyna-/policeman:polis)",
        "soru10": "Turkish people must be knowledgeable about the economic crisis over the following years.",
        "kelimeler10": "(Turkish people:Türkler/knowledgeable:bilinçli/crisis:kriz/following:gelecek/year:yıl)"
    },
    "06UygulamaTr": {
        "soru1": "Adam 10 dakika önce zarfı verdi.",
        "kelimeler1": "(man/envelope/give/ago)",
        "soru2": "Babam kaba bir adam gibi görünebilir.",
        "kelimeler2": "(rude/look)",
        "soru3": "Sütü cam şişede saklamalısınız.",
        "kelimeler3": "(milk/glass/bottle/keep)",
        "soru4": "(ilerde) Cihaz bu koşullar altında hata verir.",
        "kelimeler4": "(device/condition/error/give)",
        "soru5": "Düğmeyi baş parmağınla kapatabilirsin.",
        "kelimeler5": "(button/thumb/shut)",
        "soru6": "Amcam kahveyi geçen yıl Yemen'den getirdi.",
        "kelimeler6": "(uncle/coffee/last year/bring)",
        "soru7": "Her yaz tatili boyunca bu pastanede buluşuruz.",
        "kelimeler7": "(every/summer/holiday/patisserie/meet)",
        "soru8": "(yönetim izin verse) Evde timsah beslerim.",
        "kelimeler8": "(house/crocodile/feed)",
        "soru9": "Bir yatırımcı bu platformda şirketi için yetenekli mühendisler bulabilir.",
        "kelimeler9": "(investor/factory/competant/engineer/find)",
        "soru10": "Hayallerim için para kazanmak zorundayım.",
        "kelimeler10": "(dream/money/earn)"
    },
    "06UygulamaEn": {
        "soru1": "He can talk about the Ottoman history during the lecture.",
        "kelimeler1": "(talk:konuş-/Ottoman:Osmanlı/history:tarih/lecture:söyleşi)",
        "soru2": "The economy is rapidly growing thanks to the new management plan.",
        "kelimeler2": "(rapid:hızlı/grow:büyü-/new:yeni/management:yönetim)",
        "soru3": "The president may terminate a contract without any confirmation.",
        "kelimeler3": "(president:başkan/terminate:fesh et-/contract:sözleşme/confirmation:onay alma)",
        "soru4": "The Swiss scientists did find a new cure for this hereditary disease.",
        "kelimeler4": "(Swiss:İsviçreli/scientist:bilim insanı/new:yeni/cure:tedavi/hereditary:kalıtsal/disease:hastalık)",
        "soru5": "You can see many birds of different kinds in this small tea garden.",
        "kelimeler5": "(see:gör-/many:birçok/different:farklı/kind:tür/small:küçük)",
        "soru6": "Our company does provide many advantages to you for your financial needs.",
        "kelimeler6": "(company:şirket/provide:sağla-/financial:finansal/need:ihtiyaç)",
        "soru7": "We do intensively take English lesson at the course on Saturdays.",
        "kelimeler7": "(intensive:yoğun/take:almak(ders)/course:kurs)",
        "soru8": "My sister was watering the flowers in the backyard with a punctured hose.",
        "kelimeler8": "(water:sula-/flower:çiçek/backyard:avlu/punctured:patlak/hose:hortum)",
        "soru9": "I did clean my shoes with a cloth at school.",
        "kelimeler9": "(clean:temizle-/shoes:ayakkabı/cloth:bez)",
        "soru10": "They will put their uniforms in the chest after the graduation.",
        "kelimeler10": "(put:koy-/chest:sandık/graduation:mezuniyet)"
    },
    "07UygulamaTr": {
        "soru1": "Orduyu tasfiye etmek zorundayız.",
        "kelimeler1": "(army/disband)",
        "soru2": "Değerlendirme formuna adresini hecelemen lazım.",
        "kelimeler2": "(evaluation/spell)",
        "soru3": "Hırsızı öğlen aramda garajda yakaladım.",
        "kelimeler3": "(thief/lunch break/garage/arrest)",
        "soru4": "İsteklerini bir kağıda not almalı.",
        "kelimeler4": "(jot down/request/a piece of)",
        "soru5": "Balayı için St. Pietro-ya gideriz.",
        "kelimeler5": "(honeymoon/go)",
        "soru6": "Arkadaşlarımızla kütüphanede kitapları düzenledik.",
        "kelimeler6": "(friend/library/book/organise)",
        "soru7": "Bu sorunu dikkatli bir şekilde çözmeliyiz.",
        "kelimeler7": "(problem/cautiously/solve)",
        "soru8": "Düşmanlar memleketi işgal etti.",
        "kelimeler8": "(Enemy/fatherland/occupy)",
        "soru9": "Bozuk etten dolayı karnın ağrıyabilir.",
        "kelimeler9": "(rotten/meat/stomach/ache)",
        "soru10": "Sunum boyunca alfabetik sırada oturduk.",
        "kelimeler10": "(presentation/alphabetical/order/sit)"
    },
    "07UygulamaEn": {
        "soru1": "The emperor has to take this important decision for his nation.",
        "kelimeler1": "(emperor:imparator/take:al-/important:önemli/decision:karar/nation:millet)",
        "soru2": "You should urgently call the police in this situation.",
        "kelimeler2": "(urgent:acil/call:ara-/situation:durum)",
        "soru3": "These ultraviolet lights can cure physical disorders in a short time.",
        "kelimeler3": "(light:ışık/cure:tedavi et-/disorder:rahatsızlık)",
        "soru4": "The little monster did scare the guests in the lobby.",
        "kelimeler4": "(little:küçük/monster:canavar/scare:korkut-/guest:misafir/lobby:lobi)",
        "soru5": "They had better leave the village with their belongings before midnight.",
        "kelimeler5": "(leave:terket-/village:köy/belonging:eşya/midnight:geceyarısı)",
        "soru6": "The servant must silently close the door after the last guest.",
        "kelimeler6": "(servant:hizmetçi/silent-:sakin/close:kapat-/door:kapı/last:son/guest:misafir)",
        "soru7": "The opposition parties should consider our national unity instead of denigrating.",
        "kelimeler7": "(opposition:muhalefet/consider:düşün-/national:milli/unity:birlik/denigrate:kötüle-)",
        "soru8": "This new vaccine can neutralize flu in a short time.",
        "kelimeler8": "(new:yeni/vaccine:aşı/neutralize:etkisiz hale getir-/flu:grip)",
        "soru9": "TOGG will produce cost-efficient cars for unwealthy people.",
        "kelimeler9": "(produce:üret-/cost-efficient:uygun maliyetli/car:araba/unwealthy:varlıklı olmayan/people:insanlar)",
        "soru10": "Everybody can easily learn English with regular implementation.",
        "kelimeler10": "(Everybody:herkes/easy:kolay/learn:öğren-/regular:düzenli/implementation:uygulama)"
    },
    "08UygulamaTr": {
        "soru1": "Genç sürücüler kaygan bir yolda araçlarını dikkatli sürmeli.",
        "kelimeler1": "(young/driver/slippery/road/car/careful/drive)",
        "soru2": "Oyuncular bu kaotik ortam-da takım arkadaşlarına saygı göstermek zorunda.",
        "kelimeler2": "(player/chaotic/team/mate/respect)",
        "soru3": "Kişisel dosyalarımı eski bilgisayarımda saklıyorum.",
        "kelimeler3": "(personal/file/old/computer/keep)",
        "soru4": "Anahtar deliğinden sokağı net görebiliriz.",
        "kelimeler4": "(key/hole/clear/street/see)",
        "soru5": "Grup çalışması için sandalyeleri yerleştirdik.",
        "kelimeler5": "(situate:yerleştir-)",
        "soru6": "İnsanlar karamsar düşünceleri yüzünden tartışabilir.",
        "kelimeler6": "(people/argue/pessimistic/thought)",
        "soru7": "Yazıcı için mürekkep temin edebilir misin?",
        "kelimeler7": "(printer/ink/provide)",
        "soru8": "Hassas sindirim sistemimden dolayı et tüketmiyorum.",
        "kelimeler8": "(sensitive/digestive system/meat/consume)",
        "soru9": "Teklifi kibarca reddetmem lazım.",
        "kelimeler9": "(offer/kind/reject)",
        "soru10": "Öğretmenler çocuk istismarına karşı önlem almalı.",
        "kelimeler10": "(teacher/child abuse/precaution/take)"
    },
    "08UygulamaEn": {
        "soru1": "Flowers do really look colorful in this season.",
        "kelimeler1": "(Flower:çiçek/look colorful:renkli görün-/really:gerçekten/season:mevsim)",
        "soru2": "Children do sit next to their parents on the plane.",
        "kelimeler2": "(children:çocuklar/sit:otur-/parent:ebeveyn/plane:uçak)",
        "soru3": "The minority report does clearly show the recent progress in Turkey.",
        "kelimeler3": "(minority:azınlık/report:rapor,/clear:açık/show:göster-/recent:son/progress:gelişme)",
        "soru4": "The client may demand an upgraded version from an alternative supplier.",
        "kelimeler4": "(client:müşteri/demand:iste-/upgraded:güncellenmiş/version:sürüm/supplier:tedarikçi)",
        "soru5": "He can transform her world into a paradise with his love.",
        "kelimeler5": "(transform:dönüştür-/world:dünya/paradise:cennet)",
        "soru6": "I should thoroughly analyze the findings in one week.",
        "kelimeler6": "(thoroughly:derinlemesine/analyze:analiz et-/finding:bulgu/week:hafta)",
        "soru7": "She does occasionally visit the old-aged pensioners home on Sundays.",
        "kelimeler7": "(occasional:ara sıra olan/visit:ziyaret et-/old-aged pensioners home:huzurevi/Sundays:Pazar günleri)",
        "soru8": "Your accent will certainly improve with your intonation technique.",
        "kelimeler8": "(accent:aksan/certainly:kesinlikle/impove:geliş-/intonation:ses tonu/technique:teknik)",
        "soru9": "Dairy products do strengthen your bones.",
        "kelimeler9": "(dairy:mandıra/süt/product:ürün/strengthen:güçlendir-/bone:kemik)",
        "soru10": "The facility management did restrict the electricity use in some districts.",
        "kelimeler10": "(facility:tesis/management:yönetim/restrict:kısıtla-/use:kullanım/some:bazı/district:bölge)"
    }
};
