
var soruvekelimeler = {
    "25UygulamaEn": {
        "soru1": "This part is going to be encoloured with a special technique.",
        "kelimeler1": "(part:kısım / encolour: renklendir- / special:özel / technique: teknik)",
        "soru2": "These rumours will be revealed by the local newspaper in two days.",
        "kelimeler2": "( rumour: söylenti/ reveal: ifşa et-/ local: yerel / newspaper: gazete )",
        "soru3": "Some strict precautions should be taken by the public against this new virus.",
        "kelimeler3": "(strict: katı / precautions: önlem / public: halk)",
        "soru4": "The statue between the theatre and the pharmacy has been painted.",
        "kelimeler4": "(statue: heykel / theatre: tiyatro / pharmacy: eczane / paint: boya-)",
        "soru5": "The encyclopedia on the shelf was slily stolen by the librarian last year.",
        "kelimeler5": "(shelf:raf / slily: çaktırmadan(sinsice) / steal:çal- / librarian: kütüphane memuru)",
        "soru6": "My favourite song in my Spotify list was played on the radio.",
        "kelimeler6": "(favourite: en sevdiğim (favori) / play: çal- / radio: radyo)",
        "soru7": "The bank in the square has been robbed.",
        "kelimeler7": "(square: meydan / rob: soy-)",
        "soru8": "These medicines should be regularly taken by the patients.",
        "kelimeler8": "(medicine: ilaç/regular-: düzenli / take: al- / patient: hasta)",
        "soru9": "Anıtkabir is visited by millions of people every year.",
        "kelimeler9": "(visit: ziyaret et-)",
        "soru10": "French is spoken in Quebec province of Canada.",
        "kelimeler10": "(province:eyalet)"
    },
    "25UygulamaTr": {
        "soru1": "Bu haber yasaklanmalı.",
        "kelimeler1": "(news / ban)",
        "soru2": "Bu yaklaşım kabul edilemez.",
        "kelimeler2": "(approach / accept)",
        "soru3": "Yarın kovulabilirsin.",
        "kelimeler3": "(fire)",
        "soru4": "Sonuçlar bugün duyurulur.",
        "kelimeler4": "(result / announce)",
        "soru5": "Tabaklar kırılabilir.",
        "kelimeler5": "(plate / break)",
        "soru6": "Lobide bekleniyorsunuz.",
        "kelimeler6": "(wait / lobby)",
        "soru7": "Kocam kız kardeşini affetme konusunda ikna edilmek zorunda.",
        "kelimeler7": "(husband / sister / forgive / convince)",
        "soru8": "Engelli kullanıcılar için yeni bir cihaz tasarlansa iyi olur.",
        "kelimeler8": "(handicapped / user / new / device / design)",
        "soru9": "Pencere 5 saniye içinde kapatılacak.",
        "kelimeler9": "(window / close)",
        "soru10": "Evin her köşesi antika eşyalarla döşenmeli.",
        "kelimeler10": "(house / corner / antique / furnish / thing)"
    },
    "26UygulamaEn": {
        "soru1": "We have taken some money from the safe for our personal spendings.",
        "kelimeler1": "(take: al- / safe: kasa / spend: harca-)",
        "soru2": "I had to stay in the house to take care of the baby.",
        "kelimeler2": "(take care of: ile ilgilen-)",
        "soru3": "The orphan child was adopted by a rich couple.",
        "kelimeler3": "(couple: çift / adopt: evlat edin- / orphan: yetim)",
        "soru4": "The attorney was imprisoned that day.",
        "kelimeler4": "(hear:duy- / attorney: avukat / imprison: hapse at-)",
        "soru5": "Who should have helped you?",
        "kelimeler5": "(help: yardım et-)",
        "soru6": "He is loved by everyone because of his generous heart.",
        "kelimeler6": "(generous: cömert / heart: kalp, yürek)",
        "soru7": "The cat was not noticed before starting the engine.",
        "kelimeler7": "(notice: farket- / start: başlat, çalıştır / engine: motor)",
        "soru8": "Your membership may be cancelled as a result of this incident.",
        "kelimeler8": "(membership: üyelik / cancel: iptal et- / incident: olay)",
        "soru9": "She is going to be fired.",
        "kelimeler9": "(fire: kov-)",
        "soru10": "The book has been translated to 7 languages since the publish date.",
        "kelimeler10": "(translate: çevir- / publish date: yayın tarihi)"
    },
    "26UygulamaTr": {
        "soru1": "Ofisimize bir sekreter istihdam edilecek.",
        "kelimeler1": "(office / secretary / employ)",
        "soru2": "Depremzedeler için yeni bir yasa çıkarılabilir.",
        "kelimeler2": "(earthquake victim / new / law / enact)",
        "soru3": "Meblağ 8 gün içinde ödenmeli.",
        "kelimeler3": "(amount / day / pay)",
        "soru4": "Bu masum bebek için uygun bir yaşam alanı yaratılmak zorunda.",
        "kelimeler4": "(innocent / baby / proper / life space / create)",
        "soru5": "Orhan Pamuk'un son romanı yarından itibaren D&R'da satışa sunulacak.",
        "kelimeler5": "(latest / novel / starting tomorrow / sale / put up)",
        "soru6": "Saldırıdan sonra bölgeye takviye birlik gönderildi.",
        "kelimeler6": "(attack / area / reinforcing unit / send)",
        "soru7": "Bu çiçek her sabah sulanmalı.",
        "kelimeler7": "(flower / morning / water)",
        "soru8": "Etkinliğin saati ana haber bülteninde belli olur.",
        "kelimeler8": "(event / time / main news bulletin / clear)",
        "soru9": "Fatura yanlış isme kesilmiş.",
        "kelimeler9": "(invoice / wrong / name / issue)",
        "soru10": "Yoğurt sütten yapılır.",
        "kelimeler10": "(yoghurt / milk / make / of: -den)"
    },
    "27UygulamaEn": {
        "soru1": "I am having an adaptation problem.",
        "kelimeler1": "(have: çek-yaşa- / adaptation: uyum(adaptasyon))",
        "soru2": "This issue has been exaggerated by the media.",
        "kelimeler2": "(issue: mesele / exaggerate: abart-)",
        "soru3": "Thanks to this electrical mechanism, blood is easily pumped to the brain.",
        "kelimeler3": "(blood: kan / pump: pompala-)",
        "soru4": "Bones should not be given to cats.",
        "kelimeler4": "(bone: kemik / give: ver-)",
        "soru5": "Its reason is picked flowers.",
        "kelimeler5": "(its: onun / reason: sebep / pick: kopar- (topla-)",
        "soru6": "The divorced man purchased a destroyed house.",
        "kelimeler6": "(divorce: boşa- / purchase: satın al- / destroy: yık-)",
        "soru7": "Read only the underlined parts, please!",
        "kelimeler7": "(underline: alt(ını) çiz-)",
        "soru8": "Happy is in the house.",
        "kelimeler8": "(Happy özel isim olarak kullanılmıştır.)",
        "soru9": "The new applicant was waiting for me in the waiting room.",
        "kelimeler9": "(applicant: aday / wait: bekle- / waiting room: bekleme odası)",
        "soru10": "In Sinop, you do not need to avoid traffic jam.",
        "kelimeler10": "(need: ihtiyaç duy- / avoid-den kaçın- / traffic jam: trafik sıkışıklığı)"
    },
    "27UygulamaTr": {
        "soru1": "Kobani'de şimdiye kadar 750 müslüman öldürüldü.",
        "kelimeler1": "(until now / muslim / kill)",
        "soru2": "İnşaat yoğun protestolar sebebiyle iptal edildi.",
        "kelimeler2": "(construction / intensive / protest / cancel)",
        "soru3": "Mektuplar bugün gönderilecek.",
        "kelimeler3": "(letter / send)",
        "soru4": "Çanta ıssız bir parkta bırakılmıştı.",
        "kelimeler4": "(desolate / leave)",
        "soru5": "Bu hafta 5 kişi işten çıkarıldı.",
        "kelimeler5": "(fire)",
        "soru6": "Uzay mühendisleri tarafından yeni bir gezegen bulundu.",
        "kelimeler6": "(space engineer / new / planet / find)",
        "soru7": "Bebeğe güzelliğinden dolayı mı bu isim verildi?",
        "kelimeler7": "(baby / beauty / name / give)",
        "soru8": "Hakemin tecrübesi kurul üyeleri tarafından çabuk farkedildi.",
        "kelimeler8": "(referee / experience / council / member / quick / notice)",
        "soru9": "Teklife konaklama masrafları ilave edilebilir miydi?",
        "kelimeler9": "(offer / accommodation / cost / add)",
        "soru10": "Bazı yolsuzluklar kişisel çıkarlar için görmezden geliniyor.",
        "kelimeler10": "(corruption / personal / interest / ignore)"
    },
    "28UygulamaEn": {
        "soru1": "The advanced level of the game must have fascinated the gamers.",
        "kelimeler1": "(advanced level: ileri seviye / fascinate: hayran bırak-)",
        "soru2": "I could not have rejected this crazy offer.",
        "kelimeler2": "(reject: reddet- / offer: teklif)",
        "soru3": "They may have enrolled in a different college.",
        "kelimeler3": "(different: farklı / enroll: kayıt al-)",
        "soru4": "She will have left the area before the cops.",
        "kelimeler4": "(leave: terket- / area:bölge / cop: polis)",
        "soru5": "Convincing the shop owners about the design of the mall has not been easy.",
        "kelimeler5": "(convince: ikna et- / owner: sahip / mall: alışveriş merkezi / easy, kolay)",
        "soru6": "The format of the programme was discussed during the meeting.",
        "kelimeler6": "(discuss: tartış-)",
        "soru7": "A man living in Indonesia has wrestled with a gorilla.",
        "kelimeler7": "(Indonesia: Endonezya / wrestle:güreş-)",
        "soru8": "The aggressive sale strategy of the general director has drawn the reaction of the CEO.",
        "kelimeler8": "(aggressive: agresif / director: müdür / draw: (dikkat/tepki) çek- / reaction: tepki)",
        "soru9": "The new law about changing the name of the bridge has been accepted by the consensus.",
        "kelimeler9": "(law: kanun / change:değiştir- / bridge:köprü / accept: kabul et- / consensus: oybirliği)",
        "soru10": "Football is played with 22 players running after 1 ball.",
        "kelimeler10": "(run:kos- / after: -nın peşinden)"
    },
    "28UygulamaTr": {
        "soru1": "Üretici ciddi bir hata yapmış olmalı.",
        "kelimeler1": "(producer / serious / mistake / make)",
        "soru2": "Bu bakış açısı ile problemin kaynağına inmiş olacaksınız.",
        "kelimeler2": "(point of view / source / go down to: -e/a inmek)",
        "soru3": "Ormanda aniden bir ayı ile karşılaşmış olamaz mıyım?",
        "kelimeler3": "(forest / sudden / bear / face)",
        "soru4": "Siparişiniz yarın sabah faturasıyla size ulaşmış olur.",
        "kelimeler4": "(order / invoice / reach: -e ulaşmak)",
        "soru5": "Bu ayın sonunda borcumuzu tamamen kapatmış olacağız.",
        "kelimeler5": "(end / month / debt / complete- / clear: (borç) kapat-)",
        "soru6": "Kurye seni otelin önünde bekliyor olacak.",
        "kelimeler6": "(courier / wait)",
        "soru7": "Bu önemli ayrıntıyı atlamış olamazsın!",
        "kelimeler7": "(important / detail / skip)",
        "soru8": "Program yayından kaldırılmış olabilir.",
        "kelimeler8": "(program / remove / broadcasting)",
        "soru9": "Dolandırıcılar tarafından kötü kandırılmıştık.",
        "kelimeler9": "(swindler / bad- / cheat)",
        "soru10": "Zehirlenmemiş miydin?",
        "kelimeler10": "(poison)"
    }
};
