
var soruvekelimeler = {
    "45UygulamaTr": {
        "soru1": "Söylediğin şarkı beni şaşırttı.",
        "kelimeler1": "(sing/song/bewilder)",
        "soru2": "Bu meblağı ödeyen şirket bu hizmeti alabilir.",
        "kelimeler2": "(amount/pay/company/service/get)",
        "soru3": "Odayı temizleyen personeli çağırır mısın?",
        "kelimeler3": "(room/clean/staff/summon)",
        "soru4": "Rize'den getirdiğim çayı demledim. Birlikte içelim.",
        "kelimeler4": "(bring/tea/brew/together/let)",
        "soru5": "Şalteri kapattıktan sonra çalışmaya başlayabilirsiniz.",
        "kelimeler5": "(switch / turn (N1) off)",
        "soru6": "Sayfayı yenilediğim için içeriği göremiyorum.",
        "kelimeler6": "(page / refresh/content)",
        "soru7": "Jessica son derece güzel ve zarif. Bu yüzden herkes tarafından beğeniliyor.",
        "kelimeler7": "(extremely/beautiful/graceful)",
        "soru8": "Filmdeki karakterlerin oyunculuğu oldukça kötü olmasına rağmen, onu sevdim.",
        "kelimeler8": "(acting/character/quite)",
        "soru9": "Sherlock Holmes hikayelerini yazan Arthur Conan Doyle, Edinburgh'da doğdu.",
        "kelimeler9": "(write/ be born)",
        "soru10": "Çarşamba, rehberlerin şehrin tarihi yerleri etrafında turlara çıktığı gündür.",
        "kelimeler10": "(Wednesday/tour guide/town/historical place / go on an excursion)"
    },
    "45UygulamaEn": {
        "soru1": "A limited number of guests were able to watch the 'Light Incident' which happens every equinox.",
        "kelimeler1": "(limited:sınırlı/ equinox: ekinoks/light incident:ışık olayı)",
        "soru2": "Since she gave up smoking, she has taken places in many opera stages.",
        "kelimeler2": "(give up: bırak-/take place: yer al-/stage:sahne)",
        "soru3": "There are many people who die of diseases which are easily cured because they can't afford the treatment expenses.",
        "kelimeler3": "(die of-den : öl-/cure: tedavi et-/afford: karşıla-/treatment: tedavi)",
        "soru4": "Everyone assumed that she was pregnant, but she was just overweight.",
        "kelimeler4": "(assume:zannet-, san-/pregnant:hamile/just: sadece /overweight: aşırı kilolu)",
        "soru5": "Homeopathy can be very effective for some illnesses so it has become increasingly popular.",
        "kelimeler5": "(homeopathy:homeopati/ illness:hastalık/increasingly: giderek, artarak)",
        "soru6": "Now that you know the answer, why are you asking me?",
        "kelimeler6": "(Now that/Seeing that: madem ki / answer: cevap / ask:sor-)",
        "soru7": "Our company has made a video to show the security procedures which we should follow.",
        "kelimeler7": "(security:güvenlik/ follow: takip et-,izle-)",
        "soru8": "Our previous manager who had worked as an English teacher for over fifteen years, has decided to open his own school.",
        "kelimeler8": "(over aşkın (kendisinden sonra sayı alırsa)/previous:önceki/ decide: karar ver-)",
        "soru9": "The alphabet which is used to write some Slavic languages such as Russian and Bulgarian is the Cyrillic alphabet.",
        "kelimeler9": "(Cyrillic:Kiril / Slavic: Slav/such as: gibi / Russian:Rusça / Bulgarian:Bulgarca)",
        "soru10": "Robert Holden who wrote 'Happiness Now', was the founder of Britain's first laughter clinic.",
        "kelimeler10": "(happiness: mutluluk / Britain: Britanya / laughter:kahkaha)"
    },
    "46UygulamaTr": {
        "soru1": "Her şeye rağmen, oyunun içinde kalmak önemli.",
        "kelimeler1": "(despite:- e rağmen/everything/game/stay/important)",
        "soru2": "Sistemdeki açığı suistimal etmek isteyen bir casus var.",
        "kelimeler2": "(system/gap/exploit/want/some/hacker)",
        "soru3": "Ünlü armatör yasak ilişkisi yüzünden mi öldürüldü?",
        "kelimeler3": "(ship-owner/adulterous /relationship/murder)",
        "soru4": "Bana benle ilgili sevmediğin bir şey söyler misin?",
        "kelimeler4": "(tell/ like)",
        "soru5": "Bir millet olarak, istikrarlı olmak konusunda iyi değiliz.",
        "kelimeler5": "(nation/stable/good)",
        "soru6": "Sevmediğin çocuk seninle konuşmak istiyor.",
        "kelimeler6": "(boy/talk/want)",
        "soru7": "Şehrin iki yarısını birleştiren köprüde bekledik.",
        "kelimeler7": "(wait /bridge/connect/half)",
        "soru8": "Pitbullar tarafından saldırıya uğrayan çocuk kasabamıza yakın olan hastaneye götürüldü.",
        "kelimeler8": "(attack/town/hospital)",
        "soru9": "Elinde çiçeklerle köşede oturan adamı gördüm.",
        "kelimeler9": "(hand/flower/corner/sit/man/see)",
        "soru10": "Hediye olarak, son doğum günümde Nazım Hikmet tarafından yazılan bir kitap aldım.",
        "kelimeler10": "(birthday/present/write/get)"
    },
    "46UygulamaEn": {
        "soru1": "The sheriff located 11 cameras in various corners to observe the village.",
        "kelimeler1": "(sheriff: şerif/locate: yerleştir-/various: çeşitli/corner: köşe / observe: gözlemle-/village: köy)",
        "soru2": "All fines which have been given in the last two months are for people violating coronavirus measures.",
        "kelimeler2": "(fine: para cezası / violate: ihlal et-/measure: önlem)",
        "soru3": "The criminal investigation that was conducted ended with no result.",
        "kelimeler3": "(criminal investigation: cezai soruşturma/conduct: yürüt-/end with:ile sonlan- ile noktalan-)",
        "soru4": "In Bangladesh's refugee camps, we distributed 5.000 packages which included dry food items.",
        "kelimeler4": "(Bangladesh: Bangladeş/ refugee camp: mülteci kampi/ distribute: dağıt-/include: içer- / dry food item: kuru gıda maddesi)",
        "soru5": "Zeki Müren died of a heart attack during a live program that was being broadcast in İzmir.",
        "kelimeler5": "(die of: den öl-/ heart attack: kalp krizi / broadcast: yayınla-)",
        "soru6": "I remember my twelfth birthday. It was the day when the Twin Towers were destroyed.",
        "kelimeler6": "(remember: hatırla-/ Twin Towers: ikiz Kuleler/ destroy: yık-)",
        "soru7": "We have witnessed an event surprising all guests who came from different countries.",
        "kelimeler7": "(witness: şahit ol-/ event: olay/suprising: şaşırt-/guest: misafir/different: farklı)",
        "soru8": "I can never change my behavior which distracts the people working in the same place with me.",
        "kelimeler8": "(change: değiş-/behaviour: davranış / distract: dikkat dağıt-/same: aynı)",
        "soru9": "'Have You Ever Seen A Bear With A Purple Smile?' is my favourite childhood book.",
        "kelimeler9": "(ever: hiç bu zamana kadar / purple: mor/smile:gül-) favourite: en çok sev-/childhood: çocukluk)",
        "soru10": "You must regularly attend the meetings enlightening your future.",
        "kelimeler10": "(regular-düzenli/attend:katıl-/enlighten:aydınlat-/future gelecek)"
    },
    "47UygulamaTr": {
        "soru1": "Pazartesi arabamı yıkatacağım.",
        "kelimeler1": "(wash/monday)",
        "soru2": "Geçen hafta evimizi boyattık.",
        "kelimeler2": "(last week/house/ paint)",
        "soru3": "Bob dişlerini beyazlattı; gülüşü şahane görünüyor!",
        "kelimeler3": "(tooth diş/whiten/smile/great/look)",
        "soru4": "Çamaşır makinem bozuk; onu tamir ettirmeye ihtiyacım var.",
        "kelimeler4": "(washing machine/broken/repair/need)",
        "soru5": "Trafik cezası yazmadan önce, polis bizi bekletti.",
        "kelimeler5": "(write a traffic ticket/wait/policeman-)",
        "soru6": "Başkan asistanına 5 dakika önce uçak biletini aldırdı.",
        "kelimeler6": "(president/got/assistant/ plane ticket-)",
        "soru7": "Gözlerimi test ettirmeliyim. Gözlüğe ihtiyacım olduğuna eminim.",
        "kelimeler7": "(test/glass/need/sure)",
        "soru8": "Üniversiteyi kazandığı doğru fakat o zaten çalışkan bir öğrenciydi.",
        "kelimeler8": "(student/hardwrking/already/pass)",
        "soru9": "Yağmurdan sonraki toprak kokusu beni hep huzurlu yapar.",
        "kelimeler9": "(rain/ the smell of earth/always/peaceful)",
        "soru10": "Kuraklığı engellemek için suyu israf etmemelisiniz.",
        "kelimeler10": "(drought/waste water)"
    },
    "47UygulamaEn": {
        "soru1": "I have made my tailor sew a wonderful dress.",
        "kelimeler1": "(dog: köpek/vet:veteriner/examine:muayne ettir-)",
        "soru2": "The film was too sad. It made my wife cry.",
        "kelimeler2": "(sad hüzün/cry: agla-)",
        "soru3": "My mother is a good tailor, but she doesn't sew anymore. I want to make her sew a skirt for my graduation ball.",
        "kelimeler3": "(tailor: terzi/sew: dik-/anymore: artık/skirt: /graduation ball: mezuniyet balosu)",
        "soru4": "Your hair looks damaged, I think you should get your hair cut short.",
        "kelimeler4": "(damaged yıpranmış / cut:kestir-/short:kisa)",
        "soru5": "After I got the cleaner cleaned the windows, I washed the balconies.",
        "kelimeler5": "(wash: yıka-/window.pencere / cleaner.temizlikci-)",
        "soru6": "The roof of Lisa's house was damaged in a storm, she had the roof repaired yesterday.",
        "kelimeler6": "(damage:zarar/repair tamir ettir-/roof:çatı)",
        "soru7": "The teacher made all students rewrite their essays because the first drafts were not acceptable.",
        "kelimeler7": "(rewrite: tekrar yaz-/paper: kağıt/draft: taslak / acceptable: kabul edilebilir)",
        "soru8": "I'll have my assistant call you to reschedule the appointment.",
        "kelimeler8": "(appointment: randevu/reschedule: yeniden planla-/ call: ara-)",
        "soru9": "I had the insurance agency make a health insurance.",
        "kelimeler9": "(insurance agent: sigorta acentası/health insurance: sağlık sigortası)",
        "soru10": "I had the children do their homework before they went out.",
        "kelimeler10": "(homework:ev ödevi/out:dışan/children:çocuklar)"
    },
    "48UygulamaTr": {
        "soru1": "Sunumdaki öğretim üyesi salondaki tüm öğrencilerin değerli olduğunu dile getirdi.",
        "kelimeler1": "(presentation/lecturer/hall/valuable / utter)",
        "soru2": "Ona bir şey söylememesi için yalvardı.",
        "kelimeler2": "(beg)",
        "soru3": "Üçüncü katta mahsur kalan kızı itfaiye ekipleri kurtardı.",
        "kelimeler3": "(third floor/trap)",
        "soru4": "Dostoyevski en iyi romanını bunalım döneminde yazdığını anlattı.",
        "kelimeler4": "(novel/depression/period/write/tell)",
        "soru5": "Ünlü sanatçı şelaleye varınca, dünyadaki cennette olduğunu ifade etti.",
        "kelimeler5": "(artist/waterfall / arrive at-e : var-/world/paradise / express)",
        "soru6": "Babam, annemin ve kendisinin bu köyde doğup büyüdüklerini söylerdi.",
        "kelimeler6": "(saybe /born/grow up / village)",
        "soru7": "O büyük insan, bilimin insanlık için vazgeçilmez olduğunu vurguluyor.",
        "kelimeler7": "(great/emphasize/science/humanity/indispensable)",
        "soru8": "Seyahat acentası otelde gerçekten rahat hissedeceğimizin garantisini verdi.",
        "kelimeler8": "(travel agency/really/comfortable / assure)",
        "soru9": "Doktor annemin çabuk iyileşeceğini söyledi.",
        "kelimeler9": "(recover/quickly)",
        "soru10": "Atatürk \"Öğretmen bir mum gibidir. Diğerlerini aydınlatmak için kendini tüketir.\" dedi.",
        "kelimeler10": "(candle/consume/light)"
    },
    "48UygulamaEn": {
        "soru1": "The landlord said that the housebreakers robbed the mansion because the door had not been properly fixed.",
        "kelimeler1": "(landlord: mülk sahibi/housebreaker: hırsız (ev soyan) /rob: soy-/mansion: malikane / properly: doğru düzgün)",
        "soru2": "Peter announced that he would not give up until that factory was shut down.",
        "kelimeler2": "(announce: duyur-/ give up: pes et-/ shut down: kapat-)",
        "soru3": "Scientists have proclaimed that robots will have replaced humans by 2040.",
        "kelimeler3": "(proclaim: beyan et- (duyur-)/replace: yerini al-)",
        "soru4": "Many citizens believe that people are going to be controlled by microchips inserted in their bodies.",
        "kelimeler4": "(citizen: vatandaş / believe: inan-/control: yönet-/microchip: mikroçip / insert: yerleştir-/body: vücut)",
        "soru5": "The famous dietitian known by millions of people has claimed that cocoa beans lead to addiction.",
        "kelimeler5": "(dietitian: diyetisyen/claim: öne sür-/cocoa bean: kakao çekirdeği/lead to-e : sebep ol-/ addiction: bağımlılık)",
        "soru6": "Mr. Hardman, whose sister is one of the leading experts in this country, talked about the dangers of the virus.",
        "kelimeler6": "(leading expert: önde gelen uzman)",
        "soru7": "Is this the hotel where you are staying for the tournament?",
        "kelimeler7": "(tournament: turnuva)",
        "soru8": "It was midnight when the first rescue team arrived at the scene of the accident.",
        "kelimeler8": "(rescue team: kurtarma ekibi/ scene: sahne, mahal)",
        "soru9": "She said that she was very tired and couldn't come with me.",
        "kelimeler9": null,
        "soru10": "The intensive researches have revealed that a gigantic meteorite is going to crash the Earth in 2030.",
        "kelimeler10": "(research: araştırma / reveal: ortaya koy-/gigantic: devasa/meteorite: göktaşı / crash: çarp-/the Earth: dünya)"
    }
}
