
var soruvekelimeler = {
    "33UygulamaEn": {
        "soru1": "Each team in the league has been punished due to the vandalism of their fans.",
        "kelimeler1": "(each: her/punish: cezalandır-/vandalism: barbarlık/vandallık)",
        "soru2": "The computer has to be formatted within three days.",
        "kelimeler2": "(format: biçimlendir-/ within: İçerisinde)",
        "soru3": "This model of the car is preferred by special customers.",
        "kelimeler3": "(model: model/special: özel /customer: müşteri / prefer: tercih et-)",
        "soru4": "The 2028 Olympic Games are going to be held in Los Angeles.",
        "kelimeler4": "(olympic: olimpiyat / hold: düzenle-)",
        "soru5": "This commercial has been sponsored by Coca Cola.",
        "kelimeler5": "(commercial: reklam/ sponsor: (finansal olarak) destekle-)",
        "soru6": "The guests are being invited to the opening of the new theatre.",
        "kelimeler6": "(invite: davet et-/opening:açılış)",
        "soru7": "Many science-fiction films were directed by Steven Spielberg.",
        "kelimeler7": "(science-fiction: bilim kurgu/direct: yönet-)",
        "soru8": "The door has been locked by the doorman.",
        "kelimeler8": "(lock: kilitle/doorman: kapıcı)",
        "soru9": "In the next decade, 4 million domestic cars will have been produced.",
        "kelimeler9": "(domestic: yerli / produce: üret/next: gelecek(önümüzdeki) / decade: 10 yıl)",
        "soru10": "My daughter may be hired thanks to her efforts.",
        "kelimeler10": "(daughter: kız (evlat)/ hire: işe al-/effort: çaba)"
    },
    "33UygulamaTr": {
        "soru1": "Şimdi, Arif kumarhanedeki kaybından dolayı ağlıyor.",
        "kelimeler1": "(cry/casino/loss)",
        "soru2": "Dilimizi anlamıyor ama acımızı paylaşabiliyor.",
        "kelimeler2": "(language/understand/pain/share)",
        "soru3": "Paketi müşteriye teslim etmeden önce, imzasını almalısın.",
        "kelimeler3": "(package/customer/deliver/signature/take)",
        "soru4": "İspanyol yıldız, Messi'yi çalımladıktan sonra kaleci tarafından düşürüldü.",
        "kelimeler4": "(Spanish/star/dribble/goal keeper / pull down)",
        "soru5": "Mektubu okudum ve hemen doktoru aradım.",
        "kelimeler5": "(letter/readx2:read/doctor/call)",
        "soru6": "Bu riski aldıktan sonra onu boşayabilirsin.",
        "kelimeler6": "(risk/take/ divorce)",
        "soru7": "Röportajı gazetenin üçüncü sayfasında görebildim.",
        "kelimeler7": "(interview/newspaper/third/page/see)",
        "soru8": "Yaramazlığı yüzünden annesi çocuğu uyardı.",
        "kelimeler8": "(naughtiness/kid / warn)",
        "soru9": "Marifetli elleriyle, 1 hafta içinde bu köhne evi cennete dönüştürdü.",
        "kelimeler9": "(diligent/hand/week/ratty/house/paradise/transform)",
        "soru10": "Maalesef, satranç ve kağıt oyunlarında berbatım.",
        "kelimeler10": "(unfortunately/chess/card/game/awful)"
    },
    "34UygulamaEn": {
        "soru1": "The owner of the property is going to carry the issue to the court and demand a considerable compensation.",
        "kelimeler1": "(property: mülk/carry: taşı-/considerable: hatrı sayılır/compensation: tazminat)",
        "soru2": "Without a radical change in that year, we could not have employed 1000 personnel.",
        "kelimeler2": "(without: olmaksızın / radical: köklü /employ: işe al-/personnel: eleman-elemanlar)",
        "soru3": "She has moved to California with her baby to have better life standards.",
        "kelimeler3": "(move: taşın-/better, daha iyi)",
        "soru4": "The press conference started with the speech of the delegate.",
        "kelimeler4": "(press conference: basın konferansı / speech: konuşma / delegate: temsilci(delege))",
        "soru5": "In this competition, you have to hold the metal ball between your thumb and index finger for 15 seconds.",
        "kelimeler5": "(competition:yarışma /hold: tut-/metal: metal/thumb: baş parmak/index finger. işaret parmak/second: saniye)",
        "soru6": "Marcus cannot reply your calls at the moment because of being in the prison.",
        "kelimeler6": "(reply: yanıtla-/call: çağrı/prison: hapishane)",
        "soru7": "Amsterdam was known as a dangerous place by foreigners.",
        "kelimeler7": "(know: bil-/dangerous: tehlikeli / foreigner: yabancı)",
        "soru8": "In my childhood, I sold lemons in bazaars and water in stadiums.",
        "kelimeler8": "(childhood: çocukluk/bazaar:Pazar/sell X2= sold: sat-)",
        "soru9": "You must regularly do sports to prevent heart attack.",
        "kelimeler9": "(heart attack: kalp krizi/prevent: önle-/regular: düzenli)",
        "soru10": "A pressure must be applied on the injured area to prevent bleeding.",
        "kelimeler10": "(bleeding: kanama/injured: yaralı/apply: uygula-/pressure: baskı/prevent: önle-)"
    },
    "34UygulamaTr": {
        "soru1": "Türkçe konuşmuyor ama onu anlayabiliyorum.",
        "kelimeler1": "(talk/understand)",
        "soru2": "Bu küçük oda için büyük bir gardrop seçemeyiz.",
        "kelimeler2": "(small/room/big/wardrobe/choose)",
        "soru3": "Pembe dizilerdeki hayatlar gerçeği yansıtmıyor.",
        "kelimeler3": "(soap operas/life(çoğul:lives)/ truth/reflect)",
        "soru4": "Bilgisayarın icadından önce insanlar notlarını deftere kaydediyordu.",
        "kelimeler4": "(invention/note/notebook/save)",
        "soru5": "Bu konu üzerine yeterince düşündüm.",
        "kelimeler5": "(think/ enough)",
        "soru6": "Köprüde onunla buluşmak için evden erken çıktım.",
        "kelimeler6": "(bridge/ meet: ile buluş / early/leave: -den ayrıl-)",
        "soru7": "Soruları hızlı çözmek için kronometreyi aktif etti.",
        "kelimeler7": "(quick-/solve/chronometer/activate)",
        "soru8": "Yerimi biliyordu ama aileme hiçbir şey söylemedi.",
        "kelimeler8": "(know/place/family/anything/tell)",
        "soru9": "ABD, Ortadoğu ülkelerine sözde barış getirecek.",
        "kelimeler9": "(the USA/ Middle East/so-called/peace/bring)",
        "soru10": "Harvard Üniversitesi'nde profesör olmak için bazı belirli aşamaları geçmek zorundasın.",
        "kelimeler10": "(professor/ definite/level/pass)"
    },
    "35UygulamaEn": {
        "soru1": "An enormous innovation is going to be done in new models of Apple in the next few years.",
        "kelimeler1": "(enormous: muazzam/ innovation: yenilik / few birkaç)",
        "soru2": "Saddam Hussein was sentenced to execution because of being responsible for the death of the Iraqi Shiites.",
        "kelimeler2": "(sentence: mahkum et-/execution: idam/ responsible (for): (-den) sorumlu/ death: ölüm/ Iraqi Shiites: Iraklı Şiiler)",
        "soru3": "A huge poster has been hung to show their admiration to the elected deputy.",
        "kelimeler3": "(huge: büyük/hang: as-/admiration: hayranlık/elect-ed: seçil-en(seçilmiş)/ deputy:milletvekili)",
        "soru4": "The audiences have been impressed with the outstanding performance of acrobat in the circus.",
        "kelimeler4": "(audience: seyirci/ impress: etkile-/outstanding: göz alıcı/ acrobat: akrobat/ circus: sirk)",
        "soru5": "The construction of the new church must be accelerated by the authorities.",
        "kelimeler5": "(construction:inşaat/church:kilise / accelerate: hızlandır-/ authorities: yetkililer)",
        "soru6": "Our planet is going to be enlightened by some artificial satellites in the future.",
        "kelimeler6": "(planet: gezegen/ enlighten:aydınlat-/artifical: yapay/ satellite: uydu)",
        "soru7": "A large quantity of coffee is produced in Brazil.",
        "kelimeler7": "(quantity: miktar/ produce: üret-/Brazil: Brezilya)",
        "soru8": "More time should be given to the new couple to think on their house.",
        "kelimeler8": "(more: daha fazla/ give: ver-/couple: çift/think:düşün-)",
        "soru9": "The papers must be scanned until Friday evening.",
        "kelimeler9": "(paper: kağıt/ scan: tara-/ Friday: Cuma)",
        "soru10": "Yesternight, the colonel ordered to create the muster-roll.",
        "kelimeler10": "(yesternight: dün gece / colonel: albay/order: emret-/muster-roll: askeri personel listesi)"
    },
    "35UygulamaTr": {
        "soru1": "Konuyu baştan anlatmak biraz zor olabilir.",
        "kelimeler1": "(subject/beginning/tell/a bit/hard)",
        "soru2": "Sar beni, ben sana kendimi feda etmişim!",
        "kelimeler2": "(hug/sacrifice)",
        "soru3": "Sehpada, sana özel bir koli var.",
        "kelimeler3": "(coffee table/special/parcel)",
        "soru4": "Bu, kaliteli ve güvenilir bir ürün değil.",
        "kelimeler4": "(quality/reliable/product)",
        "soru5": "Kimse beni kandırmaya çalışmasa iyi olur.",
        "kelimeler5": "(nobody/cheat/try)",
        "soru6": "İlişkindeki konuşulmamış ayrıntılara takılmak seni yıpratabilir.",
        "kelimeler6": "(relationship/unspoken/detail/stick around/wear (n1) down)",
        "soru7": "Atatürk, öğretmenler hakkında birçok özlü söz dile getirdi.",
        "kelimeler7": "(teacher/ wise saying/utter)",
        "soru8": "Her gün kumar oynamak kötü bir alışkanlıktır.",
        "kelimeler8": "(gamble/bad/habit)",
        "soru9": "Akşamları, kafein içeren içeceklerden uzak durmanız lazım.",
        "kelimeler9": "(caffeine/contain/beverage/avoid den kaçın-/-den uzak dur-)",
        "soru10": "Balıklar solunum yapmak için solungaçlara sahiptir.",
        "kelimeler10": "(gill/respire)"
    },
    "36UygulamaEn": {
        "soru1": "Susurluk toast and ayran have become a snack for the passengers travelling on the highway.",
        "kelimeler1": "(become: ol-/snack: ara öğün/passenger: yolcu/ travel: seyahat et-/highway: otoban)",
        "soru2": "The concert can be watched through the website of the famous singer in the New Year Eve.",
        "kelimeler2": "(watch: izle-/through: aracılığı ile/famous: ünlü / New Year Eve: Yılbaşı arifesi)",
        "soru3": "The young pianist has been elected to perform during the Istanbul Jazz Festival.",
        "kelimeler3": "(pianist: piyanist/elect: seç-/musician: müzisyen/ perform: performans sergile-)",
        "soru4": "According to first forensic findings, the security guard was killed with a knife before midnight.",
        "kelimeler4": "(first: ilk/forensic finding adli bulgu/ security guard: güvenlik görevlisi/kill: öldür-/knife: bıçak/midnight: gece yarısı)",
        "soru5": "After the foundation of Turkey, Ottoman Dynasty was exiled to different continents.",
        "kelimeler5": "(foundation: kuruluş / dynasty: hanedan/exile: sürgün et-/continent: kita)",
        "soru6": "I have dialed the operator to verify my serial number.",
        "kelimeler6": "(dial: tuşla-/operator: operatör/verify:teyit et-/serial: seri)",
        "soru7": "Answers must be written with ink by the candidates.",
        "kelimeler7": "(answer: cevap/write: yaz-/ink: mürekkep/candidate: aday)",
        "soru8": "Science has proved its importance in our daily life like healthcare, communication and energy sources.",
        "kelimeler8": "(prove: kanıtla-/importance: önem/healthcare: sağlık hizmeti/ communication: iletişim/energy source: enerji kaynağı)",
        "soru9": "Everyone should consider their existance as a priceless gift from their parents.",
        "kelimeler9": "(consider:düşün-/existance: varlık/priceless: paha biçilemez/gift: hediye)",
        "soru10": "Our virtues and failings are inseparable like force and matter.",
        "kelimeler10": "(virtue: erdem/ failing: başarısızlık/ inseparable: ayrılmaz/force: güç/matter: madde)"
    },
    "36UygulamaTr": {
        "soru1": "O gün, onu rıhtımda yalnız bıraktım.",
        "kelimeler1": "(harbour/alone/leave)",
        "soru2": "O şapkayla harika görünüyorsun.",
        "kelimeler2": "(hat/great/look great)",
        "soru3": "Senin yüzünden beni deli zannettiler.",
        "kelimeler3": "(because of/crazy/suppose)",
        "soru4": "Askerleri her sabah 5'te içtima için nöbetçi kulübesinin yanında görmeliyim.",
        "kelimeler4": "(soldier/muster/sentry box/see)",
        "soru5": "İnsanlar bu yoğun bakım ünitesinde teknolojik cihazlarla iyileştiriliyor.",
        "kelimeler5": "(intensive care unit/technological/device/cure)",
        "soru6": "Katil zanlısının kimliği saç teliyle saptanabilir.",
        "kelimeler6": "(identity/ murder suspect/establish/barba)",
        "soru7": "Çantam İstiklal caddesinde bir kapkaççı tarafından çalındı.",
        "kelimeler7": "(purse/ avenue/snatcher/steal)",
        "soru8": "Bu köyün suyu içilir, kızı sevilir.",
        "kelimeler8": "(village/drink/girl/love)",
        "soru9": "Kutular makine tarafından henüz paketlenmedi.",
        "kelimeler9": "(box/machine/yet/pack)",
        "soru10": "İlhan Mansız tarafından Senegal'e son dakikada altın gol atıldı.",
        "kelimeler10": "(golden goal/ last minute/ score: (gol) at-)"
    }
}
