
var soruvekelimeler = {
    "09UygulamaTr": {
        "soru1": "Bu, telefon numaram.",
        "kelimeler1": "(telephone/number)",
        "soru2": "Telefon numaram bu.",
        "kelimeler2": "(telephone/number)",
        "soru3": "Temel sorunumuz açlık.",
        "kelimeler3": "(fundamental/problem/hunger)",
        "soru4": "Göğüs kafesimde bir muhabbet kuşusun.",
        "kelimeler4": "(rib cage/lovebird)",
        "soru5": "Yarın büyük gün.",
        "kelimeler5": "(tomorrow/day/big)",
        "soru6": "Bugün okuldasın.",
        "kelimeler6": "(today/school)",
        "soru7": "Bu gece rakı şişesinde balık gibiyim.",
        "kelimeler7": "(tonight/rakı /bottle/fish)",
        "soru8": "Onlar benden sonra.",
        "kelimeler8": "(after)",
        "soru9": "Bu insanlar aptal değil.",
        "kelimeler9": "(stupid)",
        "soru10": "Yarın toplantı için müsaitim.",
        "kelimeler10": "(meeting/available)"
    },
    "09UygulamaEn": {
        "soru1": "This film is about a true story.",
        "kelimeler1": "(true: gerçek, doğru / story: hikaye)",
        "soru2": "The file is full with confidential documents.",
        "kelimeler2": "(file:dosya/confidential:gizli /document:belge)",
        "soru3": "It is a secret between me and him.",
        "kelimeler3": "(secret:sir)",
        "soru4": "Today, I am badly ill because of the rain.",
        "kelimeler4": "(bad: kötü, fena /ill: hasta / rain:yağmur)",
        "soru5": "A dog is always a good friend for a lonely man.",
        "kelimeler5": "(always: daima/lonely: yalnız)",
        "soru6": "Her husband is normally kind to other people.",
        "kelimeler6": "(husband:eş(erkek)/kind:kibar/other:diğer)",
        "soru7": "They do officially have the whole island.",
        "kelimeler7": "(official: resmen/ the whole: bütün/island: ada)",
        "soru8": "Her wallet is full of the banknotes.",
        "kelimeler8": "(wallet:cüzdan)",
        "soru9": "The actress is finally ready for the rehearsal.",
        "kelimeler9": "(actress:aktris / final:son/ready:hazır / rehearsal:prova)",
        "soru10": "The short movie is about homeless kids.",
        "kelimeler10": "(homeless: evsiz)"
    },
    "10UygulamaTr": {
        "soru1": "Hafta sonunu aileme ayırmak zorundayım.",
        "kelimeler1": "(weekend/family/spare)",
        "soru2": "Erbil'de dün bir patlama meydana geldi.",
        "kelimeler2": "(Erbil / explosion/occur)",
        "soru3": "Yan etkisi kısa süre içinde geçer.",
        "kelimeler3": "(side/effect/short/time/pass)",
        "soru4": "Dahi yönetmen ameliyattan sonra sinemayı bıraktı.",
        "kelimeler4": "(genius/director/surgery/cinema/quit)",
        "soru5": "Bu gezi için babama resmen yalvardım.",
        "kelimeler5": "(trip/father/beg: -e yalvarmak)",
        "soru6": "Başarı için, ödev yapmanız lazım.",
        "kelimeler6": "(success/homework)",
        "soru7": "Otobüs 15 dakika içinde Samandıra'dan stadyuma hareket eder.",
        "kelimeler7": "(bus/minute / move)",
        "soru8": "ABD yasalarına göre, bir başkan 8 yıl boyunca görevde kalabilir.",
        "kelimeler8": "(USA/kaw/according to/president/year/duty/stay)",
        "soru9": "Dün Galatasaray, sahasında Beşiktaş'a teslim oldu.",
        "kelimeler9": "(yesterday/field/surrender)",
        "soru10": "Savcı ısrarcı bir şekilde idam talep etti.",
        "kelimeler10": "(prosecutor/insistent-/execution/demand)"
    },
    "10UygulamaEn": {
        "soru1": "The movie did draw their attention by its messages.",
        "kelimeler1": "(draw: çek-/attention:dikkat /society: toplum)",
        "soru2": "After the birth, the doctors did put the baby to the incubator for 2 days.",
        "kelimeler2": "(birth: doğum/put:koymak/ incubator: küvőz)",
        "soru3": "The world does know Michigan as a very green state in the USA.",
        "kelimeler3": "(know:bil-/state: eyalet)",
        "soru4": "Who are volunteers for this holy mission?",
        "kelimeler4": "(volunteer gönüllü/holy: kutsal/mission: görev)",
        "soru5": "The doors will be open for visitors until 7.",
        "kelimeler5": "(door: kapı/ visitor: ziyaretçi)",
        "soru6": "The opposition party may not attend the session today.",
        "kelimeler6": "(Opposition: muhalefet / attend: katıl/session: oturum)",
        "soru7": "Iraqi central government did reject the dialogue attempts with Turkey and Russia.",
        "kelimeler7": "(central: merkez/government: hükümet/reject: geri çevir-/ attempt: girişim)",
        "soru8": "Despite the familial obstacles, the 2 lovers are officially married now.",
        "kelimeler8": "(obstacle: engel/lover: aşık/official-: resmi/married: evli)",
        "soru9": "His mother did consent the brain surgery after a short debate.",
        "kelimeler9": "(consent:-e razı ol-/brain: beyin /s urgery:ameliyat/short: kisa/debate: tartışma)",
        "soru10": "Before 18, you cannot have a hookah in this family garden.",
        "kelimeler10": "(hookah: nargile/have: iç-)"
    },
    "11UygulamaTr": {
        "soru1": "Bu turist Almandır.",
        "kelimeler1": "(tourist/German)",
        "soru2": "Ürkek bir güvercinsin kalbimde.",
        "kelimeler2": "(shy/pigean/heart)",
        "soru3": "Şimdi müşahede altındayım.",
        "kelimeler3": "(now/observation)",
        "soru4": "Annem fedakar bir kadındır.",
        "kelimeler4": "(mother / devoted/ woman)",
        "soru5": "Çiçek dalında güzeldir.",
        "kelimeler5": "(flower/branch/beautiful)",
        "soru6": "Şişli, İstanbul'da yoğun bir ticaret merkezidir.",
        "kelimeler6": "(busy/trade/ center)",
        "soru7": "Bu küçük köy tarihi evleri ile ünlüdür.",
        "kelimeler7": "(small/village/historical/house/ famous)",
        "soru8": "İsrail ile ipler gergindir.",
        "kelimeler8": "(rope/tense)",
        "soru9": "Habeşistan, iki düşman devlet arasında barışçıl bir ülkedir.",
        "kelimeler9": "(Ethiopia/enemy/state/peaceful/country)",
        "soru10": "Bu kitap bir harita mühendisi ile ilgilidir.",
        "kelimeler10": "(book/survey engineer/about)"
    },
    "11UygulamaEn": {
        "soru1": "Hope cannot be a method for success.",
        "kelimeler1": "(hope: umut/success: başarı)",
        "soru2": "His emotional poem did deeply affect the audience.",
        "kelimeler2": "(emotional: duygusal/ poem: şiir/ affect: etkile-/audience: seyirci)",
        "soru3": "Her satirical manner was the first reason for her dismissal yesterday.",
        "kelimeler3": "(satirical: alaycı/ manner: tavır/ first: birinci/reason: sebep/ dismissal: kovulma)",
        "soru4": "The lawyer did notice a vital mistake in the lawsuit petition before the trial.",
        "kelimeler4": "(lawyer: avukat/notice:farket-/vital: önemli/ mistake: hata/ lawsuit: dava/petition:dilekçe/)",
        "soru5": "Perfume is a well-known novel by Patrick Süskind",
        "kelimeler5": "(well-known:iyi bilinen/novel:roman)",
        "soru6": "Conscious parents do not punish their kids with prizes.",
        "kelimeler6": "(conscious: bilinçli /parent: ebeveyn/punish: cezalandır-/kid: çocuk/prize: ödül)",
        "soru7": "Can you send the new version to us today?",
        "kelimeler7": "(send: gönder-/ new: yeni/version: sürüm/today: bugün)",
        "soru8": "This does look like a typical manner for a frazzled person.",
        "kelimeler8": "(look: görün-/ like: gibi/ manner: davranış/ frazzled: paniklemiş / person: kişi/biri)",
        "soru9": "These problems can badly affect the students.",
        "kelimeler9": "(issue:konu, mesele/bad-/: kötü-/affect:etkile-/student:öğrenci)",
        "soru10": "History and nature lovers must definitely see Scotland.",
        "kelimeler10": "(history: tarih/nature:doğa/lover: sever/definite:kesin/see:gör/Scotland: İskoçya)"
    },
    "12UygulamaTr": {
        "soru1": "Bu sihirli kitabı teyzene versen iyi olur.",
        "kelimeler1": "(magical/book/aunt/give)",
        "soru2": "Örümcek korkusundan asla bahsetmez.",
        "kelimeler2": "(arachnophobia/never/mention)",
        "soru3": "İlginç tavsiyeleri hayatını değiştirebilir.",
        "kelimeler3": "(amazing/advice/life/change)",
        "soru4": "Federasyon sözcüsü herkesi sükunete davet etti.",
        "kelimeler4": "(spokesman/everybody/ silence/invite)",
        "soru5": "Yeni danışmanla Ankara'da mevcut eğitim sistemini derinlemesine tartıştık.",
        "kelimeler5": "(counsellor/existent/education/deep/discuss)",
        "soru6": "Her akşam ölmüş eşek gibi yatıyorum.",
        "kelimeler6": "(evening/dead/donkey/lie)",
        "soru7": "Soho, giriş için üyelik istiyor.",
        "kelimeler7": "(entrance/membership / require)",
        "soru8": "Öğrenciler, her sınavda kollektif bir şekilde kopya çekiyor.",
        "kelimeler8": "(student/exam/collective/cheat)",
        "soru9": "Bu sunumla müşteriyi kolayca ikna edebilirsiniz.",
        "kelimeler9": "(presentation/customer/easy/convince)",
        "soru10": "Resimde iki şirin kedi görüyorum.",
        "kelimeler10": "(picture/cute/cat/see)"
    },
    "12UygulamaEn": {
        "soru1": "Some agricultural pesticides are harmful for plants.",
        "kelimeler1": "(Agricultural: tarımsal / pesticide: ilaç/ harmful: zararlı/ plant: bitki)",
        "soru2": "My cousin is a very good partner for his new girlfriend.",
        "kelimeler2": "(cousin: kuzen/girlfriend: kız arkadaş)",
        "soru3": "Istanbul may severely change in the next 10 years.",
        "kelimeler3": "(severe: ciddi/ change: değiş-/year:yıl)",
        "soru4": "In the new planet, the scientists did discover a different type in the soil.",
        "kelimeler4": "(new: yeni/planet: gezegen/ scientist: bilim insanı/discover: keşfet-/different: farklı/type: tür/ soil: toprak)",
        "soru5": "My roommate can play guitar and sing a song at the same time.",
        "kelimeler5": "(roommate: oda arkadaşı/ play: çal-/sing: söyle-/song: şarkı/ same: aynı/ time zaman)",
        "soru6": "Their divorcement reason is tough business life.",
        "kelimeler6": "(reason: neden/ divorcement: boşanma/ tough: zorlu/business: iş/ life: hayat)",
        "soru7": "In the concert, Travis Scott did invite Kendrick Lamar to the stage for their new song.",
        "kelimeler7": "(concert: konser/invite: davet et-/stage: sahne/new yeni/song: şarkı)",
        "soru8": "You had better go and talk to a pharmacy for the prescriptions.",
        "kelimeler8": "(go: git-/talk:konuş-/pharmacy: eczane/ drug: ilaç/ prescription: reçete)",
        "soru9": "You must not interpret your nightmares in a bad way.",
        "kelimeler9": "(interpret: yorumla-/nightmare:kabus/ bad: kötü / way: şekil)",
        "soru10": "We do not talk with our clients about personal things.",
        "kelimeler10": "(talk: konuş-/client: müşteri/ personal: kişisel/ thing: şey)"
    }
};
