
var soruvekelimeler = {
    "01UygulamaTr": {
        "soru1": "İlaçlarımı düzenli olarak alırım.",
        "kelimeler1": "(pills/regular-)",
        "soru2": "Her gün 9'da öğretmenlerle buluşuruz.",
        "kelimeler2": "(every day/teachers)",
        "soru3": "Her sabah bir elma yemem lazım.",
        "kelimeler3": "(every morning/apple)",
        "soru4": "Öğrencim renkli kalemleri sever.",
        "kelimeler4": "(student/coloured/pencil)",
        "soru5": "Yarın hastayı klinikte muayene ederim.",
        "kelimeler5": "(tomorrow/patient/clinic)",
        "soru6": "Rüyalarımda bir fare görüyorum.",
        "kelimeler6": "(dream/mouse)",
        "soru7": "Ailem savaştan sonra ülkeyi terk etti.",
        "kelimeler7": "(family/war/country)",
        "soru8": "Başkan, müsteşarı deprem bölgesine gönderse iyi olur.",
        "kelimeler8": "(President/undersecretary/earthquake zone)",
        "soru9": "Minik yavruyu ıssız bir parkta buldular.",
        "kelimeler9": "(little/baby/desolate)",
        "soru10": "Yabancı bir ülkede paranı dikkatli harcamalısın.",
        "kelimeler10": "(foreign/country/money/carefully)"
    },
    "01UygulamaEn": {
        "soru1": "You would do the same thing for me in the same case.",
        "kelimeler1": "(same:aynı/thing:şey/case:durum)",
        "soru2": "The new architect did decorate the management building with antique tables.",
        "kelimeler2": "(new:yeni/architect:mimar/management:yönetim/building:bina/antique:antika/table:masa)",
        "soru3": "This mobile device does follow a company car until the destination with its artificial intelligence.",
        "kelimeler3": "(mobile device: taşınabilir cihaz/company:şirket/car:araba/destination:hedef/artificial:yapay/intelligence:zeka)",
        "soru4": "The administrative problems did occur because of the aged politicians in the parliament.",
        "kelimeler4": "(administrative:yönetimsel/aged:yaşlı/politician:politikacı/parliament:parlemento)",
        "soru5": "I did paint the wall with my students for this special organization.",
        "kelimeler5": "(wall:duvar/student:öğrenci/special:özel/organization:organizasyon)",
        "soru6": "A young university student cannot be the first candidate for this online project.",
        "kelimeler6": "(young:genç/university:üniversite/first:ilk/candidate:aday/online:çevrimiçi/project:proje)",
        "soru7": "His athletic structure did make him a successful sportsman in the continent.",
        "kelimeler7": "(athletic:atletik/structure:yapi/successful:başarılı/sportsman:sporcu/continent:kıta)",
        "soru8": "We were in the summer party next to the beach yesterday.",
        "kelimeler8": "(summer:yaz/beach:plaj/yesterday:dün)",
        "soru9": "A strong race horse is necessary for a jockey in an important horse race.",
        "kelimeler9": "(strong:güçlü/race:yarış/horse:at/jockey:jokey/important:önemli)",
        "soru10": "The referee did blow his whistle at the wrong time because of the audience pressure.",
        "kelimeler10": "(referee:hakem/whistle:düdük/wrong:yanlış/time:zaman/audience:seyirci/pressure:baskı)"
    },
    "02UygulamaTr": {
        "soru1": "Çatıdan kafama taş düştü.",
        "kelimeler1": "(roof/head/stone)",
        "soru2": "Çocuk bahçede elma topluyor.",
        "kelimeler2": "(kid/garden/apple)",
        "soru3": "Adam kart verdi.",
        "kelimeler3": "(man/card)",
        "soru4": "Ev için ütü lazım.",
        "kelimeler4": "(house/iron)",
        "soru5": "Trende arkadaşlarıyla konuşuyor.",
        "kelimeler5": "(train/friends)",
        "soru6": "Bu firmada müdür olarak çalışabilirim.",
        "kelimeler6": "(firm/manager)",
        "soru7": "Aklından sayı tut.",
        "kelimeler7": "(head/number)",
        "soru8": "Test sonuçları için hastaneye gittim.",
        "kelimeler8": "(Test/result/hospital)",
        "soru9": "Kardeşim dün arabamı yıkadı.",
        "kelimeler9": "(Sibling/yesterday/car)",
        "soru10": "Arkadaşı odaya sinirli girdi.",
        "kelimeler10": "(Friend/room/angrily/)"
    },
    "02UygulamaEn": {
        "soru1": "You should read the hand book before the operation.",
        "kelimeler1": "(hand:el/book:kitap/operation:operasyon)",
        "soru2": "My little girl is playing a game with her friend in her room.",
        "kelimeler2": "(little:küçük/girl:kız/game:oyun/friend:arkadaş/room:oda)",
        "soru3": "A good manager does solve difficult problems in chaotic situations.",
        "kelimeler3": "(good:iyi/manager:müdür/difficult:zor/chaotic:karmaşık/situations:durumlar)",
        "soru4": "This city is a famous trade center in the country.",
        "kelimeler4": "(city:şehir/famous:ünlü/trade:ticaret/center:merkez/country:ülke)",
        "soru5": "My neighbour can travel around the area in a caravan during the summer.",
        "kelimeler5": "(neighbour:komşu/area:bölge/summer:yaz)",
        "soru6": "Two windows are available in case of an emergency.",
        "kelimeler6": "(window:pencere/in case of:durumunda/emergency:acil)",
        "soru7": "We did prepare a long report about the social media use among youngsters.",
        "kelimeler7": "(long:uzun/report:rapor/youngsters:gençler)",
        "soru8": "The club owner did notice a little hole on the dance floor after the party.",
        "kelimeler8": "(Owner:sahip/little:küçük/hole:çukur/dance floor:dans pisti)",
        "soru9": "The cops did check every document in my computer at an early hour this morning.",
        "kelimeler9": "(cops:polisler/document:doküman/computer:bilgisayar/early:erken/hour:saat)",
        "soru10": "Many buildings did collapse due to severe earthquake in 1999.",
        "kelimeler10": "(building:bina/severe:şiddetli/earthquake:deprem)"
    },
    "03UygulamaTr": {
        "soru1": "Bilgisayar zayıf bağlantı yüzünden çalışmıyor.",
        "kelimeler1": "(computer/poor/connection/because of)",
        "soru2": "Mavi takım maç boyunca başarılı oynadı.",
        "kelimeler2": "(blue/team/game/successful-)",
        "soru3": "Yağmur bu sabah kesilecek.",
        "kelimeler3": "(rain/morning)",
        "soru4": "Resimde iki çocuk su içiyər.",
        "kelimeler4": "(picture/kids)",
        "soru5": "Genç adam 3 ay boyunca bir teknede yaşam mücadelesi verdi.",
        "kelimeler5": "(young/man/month/sail/life struggle)",
        "soru6": "Yol kenarında hoş bir lokantada yemek yedik.",
        "kelimeler6": "(roadside/nice/restaurant/meal)",
        "soru7": "Destanlar milli kültürümüzü anlatır.",
        "kelimeler7": "(Epic/national/culture)",
        "soru8": "Garip yaratığı bir kaptan bu adada buldu.",
        "kelimeler8": "(strange/monster/captain/island)",
        "soru9": "Köpeği bu sokakta bırakamazsın.",
        "kelimeler9": "(dog/street)",
        "soru10": "Odada / gizli bir kamera / çalışıyor.",
        "kelimeler10": "(room/hidden/camera)"
    },
    "03UygulamaEn": {
        "soru1": "Rose is preparing an alternative budget plan for the next investment.",
        "kelimeler1": "(alternative:alternatif/budget:bütçe/investment:yatırım)",
        "soru2": "Nomadic tribes travel on camels in summer from a cold country to a warm one.",
        "kelimeler2": "(nomadic:göçebe/tribe:kavim/camels:develer/cold:soğuk/warm:sıcak)",
        "soru3": "The soldiers did evacuate the hostages from the detention camp with a sudden raid.",
        "kelimeler3": "(soldier:asker/hostage:rehine/detention camp:toplama kampi/sudden:ani/raid:baskın)",
        "soru4": "The anchorman did wave to his guests with frantic eyes during the live broadcast.",
        "kelimeler4": "(anchorman:haber sunucusu/guest:konuk/frantic:telaşlı/live broadcast:canlı yayın)",
        "soru5": "Alex and Maria do cheat in the exam every time.",
        "kelimeler5": "(exam:sınav/every:her)",
        "soru6": "Our hotel has a large bed capacity.",
        "kelimeler6": "(large:geniş/bed capacity:yatak kapasitesi)",
        "soru7": "A smiling dwarf will be at the door with a red rose in his hand.",
        "kelimeler7": "(smiling:gülümseyen/dwarf:cüce/rose:gül)",
        "soru8": "The pilot did fly the plane through the clouds.",
        "kelimeler8": "(plane:uçak/cloud:bulut)",
        "soru9": "The fisherman can help you in this stormy weather.",
        "kelimeler9": "(fisherman:balıkçı/stormy:fırtınalı/weather:hava)",
        "soru10": "We did find an empty seat for the Shakira concert at the last minute this afternoon.",
        "kelimeler10": "(empty:boş/seat:yer/concert:konser/last:son/minute:dakika)"
    },
    "04UygulamaTr": {
        "soru1": "Ekibi bahçede toplamalıyız.",
        "kelimeler1": "(team/garden)",
        "soru2": "Şirket yeni proje için toplantı planlıyor.",
        "kelimeler2": "(company/new/project/meeting)",
        "soru3": "Bir gol Galatasaray'a galibiyeti getirdi.",
        "kelimeler3": "(goal/victory)",
        "soru4": "Hoca her öğrenci için özel ödev veriyor.",
        "kelimeler4": "(teacher/every/student/individual/homework)",
        "soru5": "Bu kararı ailem ile aldık.",
        "kelimeler5": "(decision/family)",
        "soru6": "Detayları hafta içinde WhatsApp grubunda paylaşacağım.",
        "kelimeler6": "(details/week/group)",
        "soru7": "İntihar bombacısı emri ilginç bir yerden aldı.",
        "kelimeler7": "(suicide/bomber/command/unexpected/place)",
        "soru8": "Logoyu Garfield'a benzettik.",
        "kelimeler8": "(logo)",
        "soru9": "Babamla her sabah balkonda bir fincan çay içerim.",
        "kelimeler9": "(father/every/morning/balcony/a cup of)",
        "soru10": "Atmosfer yatırımcıyı ürküttü.",
        "kelimeler10": "(atmosphere/investor)"
    },
    "04UygulamaEn": {
        "soru1": "These physical exercises are important for a pregnant woman.",
        "kelimeler1": "(physical:fiziksel/exercise:egzersiz-aktivite/pregnant:hamile/woman:kadın)",
        "soru2": "You cannot paraglide down this mountain without a license and an official permission.",
        "kelimeler2": "(paraglide:paraşütle atla-/license:belge/official:resmi/permission:izin)",
        "soru3": "The police helicopter did fly over the area during the bloody night.",
        "kelimeler3": "(bloody:kanlı)",
        "soru4": "We would do every thing for our students with great ambition.",
        "kelimeler4": "(every:her/thing:şey/great:büyük/ambition:azim)",
        "soru5": "The police department does protect the community every day.",
        "kelimeler5": "(community:toplum)",
        "soru6": "My cell phone is still working in spite of its damages.",
        "kelimeler6": "(cell phone:cep telefonu/in spite of:-e rağmen/damage:zarar)",
        "soru7": "Your habit does not change despite the strict warnings.",
        "kelimeler7": "(habit:alışkanlık/despite:-e rağmen/strict:katı/warning:uyarı)",
        "soru8": "I did accidentally break your heart because of my mistakes.",
        "kelimeler8": "(accidental-:tesadüf/heart:kalp/mistake:hata)",
        "soru9": "The repairman will mend your car in 2 days.",
        "kelimeler9": "(repairman:tamirci)",
        "soru10": "The municipality may take new measures for the bicycle lanes in the city.",
        "kelimeler10": "(municipality:belediye/measure:ölçü/bicycle:bisiklet/lane:şerit)"
    }
};
