
var soruvekelimeler = {
    "41UygulamaTr": {
        "soru1": "Tatilimiz ile ilgili en çok zevk aldığım şey kesinlikle yemekti.",
        "kelimeler1": "(holiday / enjoy / thing / definite- / food)",
        "soru2": "Hayatını sokaklarda yaşayarak geçiren köpek evde uyumayı sevmedi.",
        "kelimeler2": "(street / spend)",
        "soru3": "Kasaba meydanının her yerindeki güvercinler korkunç bir karmaşa yarattı.",
        "kelimeler3": "(pigeon / town / square / terrible / mess)",
        "soru4": "Bilim insanları tıpta devrim yaratacak kök hücre üzerinde çalışıyorlar.",
        "kelimeler4": "(scientist / medicine / revolutionize / stem cell / work on)",
        "soru5": "Geçen hafta sekreteri işten ayrılan Mr. Jackson yeni birini arıyor.",
        "kelimeler5": "(last / week / resign / look for)",
        "soru6": "Şirketlerine gönderilen yanlış mallar hakkında şikayette bulundular.",
        "kelimeler6": "(company / send / wrong / good / complain)",
        "soru7": "Maria'ya aşık olan Jonathan kır düğünü yapmaya karar verdi.",
        "kelimeler7": "(fall in love / countryside wedding / decide)",
        "soru8": "Müşterileri bilgilendirmeden suyu kesen teknik müdür hatasını kabul etti.",
        "kelimeler8": "(customer / inform / cut (N1) off / technical manager / fault / admit)",
        "soru9": "Programda yapılan bu saçma teklif bizi izleyen herkesi çok şaşırttı.",
        "kelimeler9": "(ridiculous / offer / watch / shock)",
        "soru10": "Seni ölümle tehdit eden adam hakkında şikayetçi olmalısın.",
        "kelimeler10": "(death / threaten / complain)"
    },
    "41UygulamaEn": {
        "soru1": "The people who study will succeed.",
        "kelimeler1": "(succeed)",
        "soru2": "I loved the cake which you made yesterday.",
        "kelimeler2": "(love / make)",
        "soru3": "You should call us when you decide.",
        "kelimeler3": "(call / decide)",
        "soru4": "A teacher who does not know Turkish cannot teach English to Turkish students.",
        "kelimeler4": "(teach)",
        "soru5": "My father saw the car which you tested yesterday on the web site.",
        "kelimeler5": "(see / test / yesterday)",
        "soru6": "The man who found my wallet was a German who lives in Istanbul.",
        "kelimeler6": "(find / wallet / German)",
        "soru7": "They are going to take you to a restaurant where only Chinese people work.",
        "kelimeler7": "(take / only / Chinese / work)",
        "soru8": "The customers who the agency sent do not want to stay in the hotel which we suggested.",
        "kelimeler8": "(customer / agency / stay / suggest)",
        "soru9": "Firing a coach who has got 2 big cups in the last 2 years would be nonsense.",
        "kelimeler9": "(fire / coach / cup / nonsense)",
        "soru10": "To complete the process, you must sign the paper which will be given to you.",
        "kelimeler10": "(complete / process / sign / paper / give)"
    },
    "42UygulamaTr": {
        "soru1": "Huzurlu olmadığın bir evde yaşamamalısın.",
        "kelimeler1": "(peaceful / house / live)",
        "soru2": "Rafa bıraktığım torbayı almak biraz zor olabilir.",
        "kelimeler2": "(shelf / leave / pouch / a bit / hard)",
        "soru3": "Senle o yolda geçirdiğim zamanları unutamıyorum.",
        "kelimeler3": "(road / spend / time / forget)",
        "soru4": "Kapıda, sana yollanmış bir hediye paketi var.",
        "kelimeler4": "(door / send / gift pack)",
        "soru5": "Birçok protestocu halkın büyük çoğunlukla seçmiş olduğu bakana itirazlarını dile getirdi.",
        "kelimeler5": "(protestor / public / majority / elect / minister / objection / verbalise)",
        "soru6": "Beni kandıran kendini kandırır. Bunu unutma!",
        "kelimeler6": "(forget / cheat / himself)",
        "soru7": "Her gün hatırladığın kötü anılar seni üzebilir.",
        "kelimeler7": "(remember / bad / memory / upset)",
        "soru8": "Sırtıma saplanan hançerin izini hala taşıyorum.",
        "kelimeler8": "(back / stab / dagger / scar / still / carry)",
        "soru9": "Dün okulumuzun çatısını onaran adam, bugün yeni bir iş teklif aldı.",
        "kelimeler9": "(roof / repair / get / job / offer)",
        "soru10": "Günün bu saatinde, kafein içeren içeceklerden uzak durmanız lazım.",
        "kelimeler10": "(caffein / beverage / avoid)",
    },
    "42UygulamaEn": {
        "soru1": "Would you like to participate in our project which we are going to start in May?",
        "kelimeler1": "(participate / start)",
        "soru2": "We are looking for pilots for our 10 new planes which we have purchased.",
        "kelimeler2": "(look / purchase)",
        "soru3": "My eyes get red when I spend a long time in front of the computer.",
        "kelimeler3": "(get red / in front of)",
        "soru4": "I do not know the person complaining about you to the police.",
        "kelimeler4": "(complain / know)",
        "soru5": "The 100 Anzachs are going to visit the lands where they lost their sons tomorrow.",
        "kelimeler5": "(anzach / visit / land / lose / son)",
        "soru6": "People who deceive others do not recognize that they deceive themselves.",
        "kelimeler6": "(deceive / people / recognize)",
        "soru7": "I have forgotten the fact that the company has gone bankrupt.",
        "kelimeler7": "(forget / company / go bankrupt)",
        "soru8": "I cut my finger when I chopped tomatoes for the salad.",
        "kelimeler8": "(salad / tomato / chop / cut)",
        "soru9": "My uncle took the chairs I repaired and placed them into the new rooms I started to decorate last year.",
        "kelimeler9": "(uncle / chair / repaire / place (N1) into / start / decorate)",
        "soru10": "The flat which we will rent should have at least three rooms.",
        "kelimeler10": "(flat / rent / at least)"
    },
    "43UygulamaTr": {
        "soru1": "İngiltereli olan Bob benim öğretmenimdir.",
        "kelimeler1": "(England / teacher)",
        "soru2": "Benim öğretmenim olan Bob İngilterelidir.",
        "kelimeler2": "(teacher / England)",
        "soru3": "Amerika'dan ayrılmadan önce, harika bir alışveriş yapacağım.",
        "kelimeler3": "(before / leave / do / great / shopping)",
        "soru4": "Ödevini evde unutan çocuk, öğretmeninden özür diledi.",
        "kelimeler4": "(boy / forget / homework / apologize)",
        "soru5": "Komşunun yeni doğan bebeği sürekli ağlıyor.",
        "kelimeler5": "(new born baby / neighbour / cry)",
        "soru6": "Ağaçtan elma toplayan çocuk düştü ve ayağını kırdı.",
        "kelimeler6": "(boy / pick up / apples / tree / fell down / broke)",
        "soru7": "NIKE'dan aldığım ayakkabıyı senelerce giydim.",
        "kelimeler7": "(wear / sneakers / buy / years)",
        "soru8": "Yağmurda ıslanan kedi ağacın altına gizlendi.",
        "kelimeler8": "(cat / wet / hide / under / tree)",
        "soru9": "Ameliyattan sonra, hastanın annesi olan kadın doktorlara teşekkür etmeyi unutmadı.",
        "kelimeler9": "(operation / patient / forget / thank)",
        "soru10": "En sevdiğim meyve olan muz, Akdeniz bölgesinde yetişir.",
        "kelimeler10": "(banana / fruit / grow / mediterranean / region)"
    },
    "43UygulamaEn": {
        "soru1": "The experience I got in Bingöl, a small city in the Southern east of Turkey, was priceless in terms of understanding the reality of life.",
        "kelimeler1": "(southern east / priceless / reality)",
        "soru2": "Stephen Hawking, the famous physicist who was diagnosed with a fatal disease, was not able to speak until a computerized system allowed him to communicate.",
        "kelimeler2": "(physicist / diagnose / fatal)",
        "soru3": "The USA witnessed rise in economy during the reign of Kennedy who was a prestigious leader of American history.",
        "kelimeler3": "(witness / reign / prestigious)",
        "soru4": "Water turbines were positioned into the tidal zone by a scientist who had been recruited by the government.",
        "kelimeler4": "(water turbine / position / tidal zone / recruit)",
        "soru5": "Due to various reasons, many people who live in Eastern Anatolia immigrate to İstanbul where employment is intense.",
        "kelimeler5": "(Eastern Anatolia / immigrate / employment / intense)",
        "soru6": "Ottoman Empire was founded in Söğüt-Domaniç region which attracts the archaeologists with its unique history.",
        "kelimeler6": "(found / attract / archaeologist / unique)",
        "soru7": "1923 was the year which inspired the Turkish patriots to set up a new regime which is called 'Republic.",
        "kelimeler7": "(inspire / patriot / set up / regime)",
        "soru8": "I know a great hotel where I can have a perfect holiday with my friend.",
        "kelimeler8": "(great / perfect / holiday)",
        "soru9": "The exams which were applied at school were mostly difficult.",
        "kelimeler9": "(exam / mostly / applied)",
        "soru10": "My daughter tries not to wake both me and her father when she leaves home.",
        "kelimeler10": "(wake / try / both... and / leaves)"
    },
    "44UygulamaTr": {
        "soru1": "Beynin fonksiyonlarını yavaşlatan bu hastalığın adı Alzheimer'dır.",
        "kelimeler1": "(brain / function / slow down / disease / name)",
        "soru2": "Sarah'nın doğum günüm için düzenlemek istediği parti hakkında konuştuk.",
        "kelimeler2": "(birthday / organize)",
        "soru3": "Jerry, yalnızca bir sayfa uzunluğunda olan makalesinden kötü bir not aldı.",
        "kelimeler3": "(one page long / essay / receive)",
        "soru4": "Kardeşini okula bırakan Ali oyun oynamaya gitti.",
        "kelimeler4": "(brother / school / leave / game / play / go)",
        "soru5": "Empati yapabilen bir satıcı her şeyi satabilir.",
        "kelimeler5": "(empathy / make / salesperson / sell)",
        "soru6": "Fren yapamayan sürücü pazara daldı.",
        "kelimeler6": "(put on the brake / driver / plough into)",
        "soru7": "Bu, filmleri her zaman büyük başarı elde eden yapımcıdır.",
        "kelimeler7": "(success / producer)",
        "soru8": "Yeni müdürün kovulmasının nedeni dakiklik sorunudur.",
        "kelimeler8": null,
        "soru9": "Seçmenler, daha yüksek vergi öneren adaya karşıydı.",
        "kelimeler9": "(vote / proposal / higher tax / candidate)",
        "soru10": "En son kaydı çok popüler hale gelen Madonna, şimdi dünyayı dolaşıyor.",
        "kelimeler10": "(recording / tour)"
    },
    "44UygulamaEn": {
        "soru1": "This ridiculous offer which she made to me in the programme shocked everyone who was watching us.",
        "kelimeler1": "(ridiculous / shock)",
        "soru2": "The person who took me to the hospital was the taxi driver who we argued with last week.",
        "kelimeler2": "(take / argue with)",
        "soru3": "In a minute, the man who the waiter scolded in the restaurant came back with a group of bandits and beat him.",
        "kelimeler3": "(scold / come back / bandit / beat)",
        "soru4": "Thanks to modern technology, people who have hearing problems are enjoying to hear with the use of aids.",
        "kelimeler4": "(hearing problem / enjoy / hear / aid)",
        "soru5": "It took me some time to find an adaptor for my computer, which I had brought back with me.",
        "kelimeler5": "(adaptor / bring back)",
        "soru6": "The story is about a young woman whose 5-year old son suddenly disappears.",
        "kelimeler6": "(disappear)",
        "soru7": "Where are the shoes which I bought yesterday?",
        "kelimeler7": "(buy)",
        "soru8": "I was wondering why the earth moves around the sun.",
        "kelimeler8": "(wonder)",
        "soru9": "The woman whose dog barks all the time lives together with her daughter.",
        "kelimeler9": "(bark)",
        "soru10": "The little student told the reason why he peed his pants in the middle of the lesson.",
        "kelimeler10": "(peed / pants / middle)"
    }
};
