
var soruvekelimeler = {
    "37UygulamaTr": {
        "soru1": "Dosyalarda bazı bilgiler buldum ve bu bilgiler kamuoyunu sarsacak.",
        "kelimeler1": "(file / data / find / public opinion / rock)",
        "soru2": "Bir müşteri içeri geldi ve sizinle görüşmek istediğini söyledi.",
        "kelimeler2": "(customer / come / want / talk)",
        "soru3": "Ceketini almak için eve gitti ve toplantıya geri geldi.",
        "kelimeler3": "(meeting / go / jacket / come)",
        "soru4": "Festivalde Kapadokya'nın tüm geleneksel yemeklerini yedim ama Testi Kebabı benim favorimdi.",
        "kelimeler4": "(traditional food / eat / Kebab / favourite)",
        "soru5": "Geçen sezon bir sunum yaptım ve seyirciler tarafından alkışlandım.",
        "kelimeler5": "(make presentation / audience / applaud)",
        "soru6": "Size bunları anlattım fakat bir şey yapmanızı beklemedim.",
        "kelimeler6": "(told / expect / anything)",
        "soru7": "Yola çok erken çıktım fakat paketi teslim edemedim.",
        "kelimeler7": "(set off / early / deliver / package)",
        "soru8": "Saatine baktı ve ders saatinin yaklaştığını farketti.",
        "kelimeler8": "(look / watch / class time / approach)",
        "soru9": "Brezilyalı yıldız derbide büyüleyici bir performans gösterdi ve herkesi hayran bıraktı.",
        "kelimeler9": "(Brazilian / star / derby / show / fascinating)",
        "soru10": "Her gün telefonda çok vakit harcıyorum, bu yüzden artık sosyal medya kullanmayacağım.",
        "kelimeler10": "(spend / social media)"
    },
    "37UygulamaEn": {
        "soru1": "The crew has found a new island and dropped an anchor near the shore.",
        "kelimeler1": "(crew: mürettebat / drop: at- / anchor: demir)",
        "soru2": "Our uncle is going to take us on Saturday morning, so we have prepared our suitcases.",
        "kelimeler2": "(uncle: amca, dayı, enişte / take: al- / prepare: hazırla- / suitcase: valiz)",
        "soru3": "I like long hair but I feel overwhelmed in hot weather.",
        "kelimeler3": "(overwhelmed: bunalmış / hot: sıcak / long: uzun / weather: hava)",
        "soru4": "He grew up without a father but he never used it as an excuse.",
        "kelimeler4": "(grow up: yetişmek / without: olmaksızın / excuse: bahane)",
        "soru5": "We went to watch the match yesterday and supported our team.",
        "kelimeler5": "(support: desteklemek / watch: izlemek)",
        "soru6": "She studied day and night so she passed the exam with a high mark.",
        "kelimeler6": "(study: çalış- / day and night: gece gündüz / pass: geç- / high: yüksek / mark: not)",
        "soru7": "I couldn't pass the exam this year but I will definitely succeed next year.",
        "kelimeler7": "(pass: geçmek / succeed: başarılı olmak / exam: sınav / definitely: mutlaka)",
        "soru8": "The relevant unit had been visited and the documents had been delivered.",
        "kelimeler8": "(deliver: teslim et- / visit: ziyaret et- / documents: evraklar)",
        "soru9": "I don't have enough time for breakfast or to take a shower.",
        "kelimeler9": "(enough: yeterince / have a breakfast: kahvaltı yap- / take a shower: duş al-)",
        "soru10": "She worked in different departments of the hospital during the war.",
        "kelimeler10": "(department: bölüm)"
    },
    "38UygulamaTr": {
        "soru1": "Sigara yasağı ile ilgili bir düzenleme yapıldı ve kapalı alanlarda sigara içmek yasaklandı.",
        "kelimeler1": "(smoking / ban / regulation / closed area / forbid)",
        "soru2": "Stadyuma vardığımızda performans çoktan başlamıştı, bu yüzden ilk iki şarkıyı kaçırdık.",
        "kelimeler2": "(get / miss)",
        "soru3": "Dinozorlar milyonlarca yıl önce dünyanın etrafında dolaştı.",
        "kelimeler3": "(dinosaur / wander)",
        "soru4": "Bir merdivenden düştü ve bileğini kırdı. Bu yüzden bir süredir okula gitmiyor.",
        "kelimeler4": "(ladder / fall off / break / for a while)",
        "soru5": "Pilot uçağı dengelemeye çalışırken alarm çaldı.",
        "kelimeler5": "(stabilize / go off)",
        "soru6": "Ekonomik kriz toplumda büyük hasar yarattı, bu yüzden insanlar mutsuz.",
        "kelimeler6": "(economical crisis / society / cause damage: hasara sebep ol- (yarat-))",
        "soru7": "Radyoda bir ses duydum ve o ses beni geçmişe götürdü.",
        "kelimeler7": "(hear / voice / take / back to past: geçmişe)",
        "soru8": "Bu kariyeri babam sayesinde elde ettim ve birçok iyi işe imza attım.",
        "kelimeler8": "(career / get / thanks to / put signature: imza at- / work)",
        "soru9": "Harika bir film izledim ve o filmdeki karakterleri hala unutamıyorum.",
        "kelimeler9": "(wonderful / character / still / forget)",
        "soru10": "Tatilimizden eve yeni geldik ve yerleşmeye çalışıyoruz.",
        "kelimeler10": "(settle in / just)"
    },
    "38UygulamaEn": {
        "soru1": "When Dad comes home from work, he wants to lie down on the sofa because he is tired.",
        "kelimeler1": "(lie down: uzan-)",
        "soru2": "The judge has sentenced many criminals in his career.",
        "kelimeler2": "(judge: yargıç, hakim / criminal: suçlu)",
        "soru3": "In the Renaissance period, there was a wide range of classical texts but some of these texts had survived only in fragments.",
        "kelimeler3": "(Renaissance: Rönesans / a wide range of: çok çeşitli / survive: hayatta kal- / only: sadece / in fragments: parçalar halinde)",
        "soru4": "The government has given a scholarship to 10 students in our school but the parents aren't delighted about the amount of money.",
        "kelimeler4": "(government: Devlet / give: ver- / scholarship: burs / delighted: memnun / amount: miktar)",
        "soru5": "The coast guard vessel passed by and saved him from drowning.",
        "kelimeler5": "(coast guard vessel: sahil güvenlik gemisi / pass by: geç- / drown: boğul-)",
        "soru6": "You must not forget to look in your pockets before you put the jacket into the washing machine.",
        "kelimeler6": "(look through: gözden geçir- / pocket: cep)",
        "soru7": "Bob deserves another chance to prove that he is the best defender in our team.",
        "kelimeler7": "(deserve: hak et- / prove: kanıtla- / defender: savunma oyuncusu)",
        "soru8": "My brother shot a video and It was viewed by more than 1 million Instagram users in two days.",
        "kelimeler8": "(shot: çek- / view: gör-, izle- / user: kullanıcı)",
        "soru9": "The immune system of the body attacks bacteria, cancer cells, other foreign substances and eliminates them.",
        "kelimeler9": "(immune system: bağışıklık sistemi / attack: saldır- / eliminate: yok et- / substance: madde / cell: hücre)",
        "soru10": "The President thinks and claims to be an expert on this subject.",
        "kelimeler10": "(claim: iddia et- / expert: uzman)"
    },
    "39UygulamaTr": {
        "soru1": "Çok uyuduğumda kendimi yorgun hissediyorum.",
        "kelimeler1": "(sleep / day / tired / feel)",
        "soru2": "Cihazı kaldırırken dikkatli olunuz.",
        "kelimeler2": "(device / lift / careful)",
        "soru3": "Mezun olana kadar para biriktirmek istiyorum.",
        "kelimeler3": "(graduate / save / money)",
        "soru4": "Eğer bu makaleyi okusaydın, insan anatomisini kolaylıkla öğrenebilirdin.",
        "kelimeler4": "(read / article / learn / human anatomy)",
        "soru5": "Vapur aniden durunca elimdeki bardağı düşürdüm.",
        "kelimeler5": "(ferry / sudden- / stop / hand / glass / drop)",
        "soru6": "Ayrılmadan önce herhangi bir şey söyledi mi?",
        "kelimeler6": "(leave / anything: herhangi bir şey (soru cümlelerinde) / say)",
        "soru7": "Yeterliliğini kanıtladığı için terfi alacak.",
        "kelimeler7": "(get a promotion / efficiency / prove)",
        "soru8": "Pandemi döneminde sokağa çıkma yasağını deldiği için polise yakalanmamaya dikkat etti.",
        "kelimeler8": "(curfew / break / catch / pay attention)",
        "soru9": "Bu sabit ofis işine başladığından beri çok kilo aldı.",
        "kelimeler9": "(sedentary / office job / weight / put on weight)",
        "soru10": "Bu güçlü güneş ışığından kendini korumak için losyon gerekli.",
        "kelimeler10": "(strong / sunlight / protect / lotion / apply / get sunburnt)"
    },
    "39UygulamaEn": {
        "soru1": "Because the Ottoman management has incisive methods, it would easily collect taxes from the public.",
        "kelimeler1": "(Ottoman: Osmanlı / management: yönetim / incisive: dokunaklı / collect: topla- / tax: vergi / public: halk)",
        "soru2": "In those years, an old man would come to our house and bring milk after we had ordered it.",
        "kelimeler2": "(bring: getir- / order: sipariş ver-)",
        "soru3": "The learning capacity of a child cannot be understood by classical methods if the child is an introvert.",
        "kelimeler3": "(understand: anla- / introvert: içe dönük)",
        "soru4": "Although she has been living in Turkey for more than 10 years, there must be a mental problem if she cannot speak Turkish.",
        "kelimeler4": "(mental: ruhsal / speak: konuş- / live: yaşa-)",
        "soru5": "Even though the owner of the new car complained about the brand to various inspection firms, he couldn't prove his being right about that issue.",
        "kelimeler5": "(complain: şikayet et- / brand: marka / various: çeşitli / inspection firm: denetim firması / prove: kanıtla- / issue: mesele)",
        "soru6": "I was reading a book in the lobby when the dog bit the vet while he was injecting it.",
        "kelimeler6": "(bite: ısır- / inject: iğne yap-)",
        "soru7": "The project of my students was not liked and accepted by the jury even though they only spent 3 months to prepare its template.",
        "kelimeler7": "(accept: kabul et- / prepare: hazırla- / template: taslak)",
        "soru8": "When I was in London, I couldn't easily approach people although I was very social.",
        "kelimeler8": "(easy-: kolay- / approach: yaklaş-)",
        "soru9": "Since she gave up smoking, she has started to save money.",
        "kelimeler9": "(give up: vazgeç- (bırak-) / since: -den beri / start: başla- / save: biriktir-)",
        "soru10": "Millions of children in these Third World Countries will die if these infectious diseases remain uncontrolled.",
        "kelimeler10": "(third: üçüncü / die: öl- / infectious: bulaşıcı / disease: hastalık / remain: kal- / uncontrolled: kontrolsüz)"
    },
    "40UygulamaTr": {
        "soru1": "Dave Afrika'da bir inşaat projesi üzerinde çalışıyorken sıtma virüsü kaptı.",
        "kelimeler1": "(construction / malaria / catch)",
        "soru2": "Yurtdışına seyahat edebilmen için geçerli bir pasaportun olmak zorunda.",
        "kelimeler2": "(abroad / travel / valid / passport)",
        "soru3": "Her apartman sakini aidatını öder ödemez yeni çatıyı inşa etmeye başlarlar.",
        "kelimeler3": "(apartment resident / contribution / pay / roof / construct)",
        "soru4": "Danışma görevlisi öğlen yemeğini bitirene kadar bir saatliğine telefonlara cevap verir misin?",
        "kelimeler4": "(receptionist / lunch / next hour / answer)",
        "soru5": "Öğrencileri zamanında geri geldiği sürece, onlara kızmaz.",
        "kelimeler5": "(students / in time / come back / get angry with: -e kız-)",
        "soru6": "Yemeğimi yerken televizyon izlemeyi seviyorum, bu yüzden genellikle oturma odasında tepside yerim.",
        "kelimeler6": "(eat / watch / tray / living room)",
        "soru7": "Videoyu izledikten sonra lütfen tüm cihazları kapatın!",
        "kelimeler7": "(watch / device)",
        "soru8": "Koli uygunsuz bir şekilde paketlenmesine rağmen çay takımı kırılmamış (olarak) geldi.",
        "kelimeler8": "(package / improperly / wrap / arrive / tea set / arrive / unbroken)",
        "soru9": "Evlendiğinden beri golf oynamadı.",
        "kelimeler9": "(get married / golf)",
        "soru10": "Baharatlı yemeklerin mideni bozma ihtimaline karşı çantana birkaç hap koysan iyi olur.",
        "kelimeler10": "(spicy / food / unsettle stomach: mide boz- / put / pill)"
    },
    "40UygulamaEn": {
        "soru1": "Although the estate agent had promised to show the family a house with a garden, he showed them the wrong flat.",
        "kelimeler1": "(complain: şikayet et- / brand: marka / inspection: denetleme / firm: şirket / prove: kanıtla- / right: haklı2 / issue: mesele)",
        "soru2": "She wasn't known as a talented singer until she sang at the school concert.",
        "kelimeler2": "(talented: yetenekli / singer: şarkıcı / sing: şarkı söyle- / concert: konser)",
        "soru3": "Since the pupils at the school were very naughty, the teacher gave them a punishment.",
        "kelimeler3": "(pupil: öğrenci / naughty: yaramaz / punish: ceza ver-)",
        "soru4": "My wife started yoga because she wanted to gain flexibility.",
        "kelimeler4": "(wife: eş (kadın) / start: başla- / gain: kazan- / flexibility: esneklik)",
        "soru5": "We all loved his performance although he didn't get any applause.",
        "kelimeler5": "(we all: hepimiz / get: al- / applause: alkış)",
        "soru6": "Herbert performed some hazardous experiments because he was curious.",
        "kelimeler6": "(perform: uygula- / hazardous: tehlikeli / experiment: deney / curious: meraklı)",
        "soru7": "You will not harm the wall if you wipe it with a moist cloth.",
        "kelimeler7": "(harm: zarar ver- / wall: duvar / wipe: sil- / moist: nemli / cloth: bez)",
        "soru8": "As soon as you hear any news, will you inform me?",
        "kelimeler8": "(hear: duy- / news: haber / inform: bilgilendir-)",
        "soru9": "Since he is a strong man, he had no trouble climbing with a heavy rucksack.",
        "kelimeler9": "(strong: güçlü / trouble: sıkıntı / climbing: tırmanma / heavy: ağır / rucksack: sırt çantası)",
        "soru10": "Though giant pandas are endangered species, human beings continue to hurt them as if they were many in number.",
        "kelimeler10":"(though: rağmen/ giant:dev / endangered: nesli tükenmekte olan / species:tür,türler / human being: insanoğlu / hurt: incit- / in number: sayıca)"}
}